ARDP: /Developer/school/ardp/src/lib/parsers/parser.c File Reference
parser.c File Reference
Data Structures
struct _cursor
struct _token
struct _parser
union _token.value
Functions
ardp_status_t ardp_parser_create ()
Create and initialize all prerequisites for shared_parser.
ardp_status_t ardp_parser_init (ardp_parser_config_t *cfg)
ardp_status_t ardp_parser_consume (ardp_token_t token)
ardp_status_t ardp_parser_set_parse_handler (void *fc)
ardp_status_t ardp_parser_set_error_handler (void *fc)
ardp_status_t ardp_parser_destroy ()
Unallocate parser after it is not necessary anymore.
ardp_parser_push ((token){RDF_BNODE,{1, 3},"_:"})
ardp_parser_pop ()
ardp_state_t ardp_parser_state ()
ardp_status_t ardp_parser_set_base_uri (utf8 *_Nonnull uri)
ardp_rdf_turtle_prefix_t * ardp_parser_prefix_find (const uint8_t *name, size_t len)
ardp_status_t ardp_parser_prefix_add (const uint8_t *name, const uint8_t *uri)
Variables
struct _cursor cursor
struct _token token
struct {
const uint8_t * uri
const uint8_t * name
} ardp_rdf_turtle_prefix
struct _parser parser
Detailed Description
Lemon based interface for the generated code.
vim: set syntax=c.doxygen
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vbs.c.nosp@m.z
Date
2016
Definition in file parser.c.
Data Structure Documentation
struct _cursor
Definition at line 13 of file parser.c.
Data Fields
size_t col
size_t line
struct _token
Definition at line 18 of file parser.c.
Data Fields
struct cursor pos
union _token value
union _token.value
Definition at line 23 of file parser.c.
Data Fields
char chr
double dbl
int i
utf8 str
Function Documentation
ardp_status_t ardp_parser_consume (ardp_token_t token)
ardp_status_t ardp_parser_create (void)
Create and initialize all prerequisites for shared_parser.
Returns
0 if successful, non-zero otherwise.
Definition at line 473 of file test_lemon.c.
References ardp_parser_create_internal(), ParseAlloc(), and shared_parser.
ardp_status_t ardp_parser_destroy (void)
Unallocate parser after it is not necessary anymore.
Destroy shared lexer. And all its underlying structures.
Definition at line 527 of file test_lemon.c.
References ardp_parser_destroy_internal(), ParseFree(), and shared_parser.
ardp_status_t ardp_parser_init (ardp_parser_config_t * cfg)
ardp_parser_pop ()
ardp_status_t ardp_parser_prefix_add (const uint8_t * name, const uint8_t * uri)
Definition at line 84 of file parser.c.
References ardp_parser_prefix_find(), ardp_parser_state(), ardp_rdf_turtle_prefix, and isnt.
ardp_rdf_turtle_prefix_t* ardp_parser_prefix_find (const uint8_t * name, size_t len)
Definition at line 73 of file parser.c.
References ardp_parser_state(), and isnt.
Referenced by ardp_parser_prefix_add().
ardp_parser_push ((token){RDF_BNODE,{1, 3},"_:"})
ardp_status_t ardp_parser_set_base_uri (utf8 *_Nonnull uri)
Definition at line 54 of file parser.c.
References ardp_parser_state(), is, isnt, string_hdr(), and string_header_t.
ardp_status_t ardp_parser_set_error_handler (void * fc)
ardp_status_t ardp_parser_set_parse_handler (void * fc)
ardp_state_t ardp_parser_state ()
Definition at line 50 of file parser.c.
Referenced by ardp_parser_prefix_add(), ardp_parser_prefix_find(), and ardp_parser_set_base_uri().
Variable Documentation
struct { ... } ardp_rdf_turtle_prefix
Referenced by ardp_parser_prefix_add().
struct _cursor cursor
struct _parser parser
struct _token token
Referenced by transform_uri().