ARDP: /Developer/school/ardp/tests/check_lexer_turtle.c File Reference
check_lexer_turtle.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <errno.h>
#include <iso646.h>
#include <string.h>
#include <assert.h>
#include <dispatch/dispatch.h>
#include <ardp/lexer.h>
#include <ardp/util.h>
#include <ardp/color.h>
#include <ardp/parser.h>
#include <zlib.h>
#include <bzlib.h>
#include <unistd.h>
Functions
static int lexer_error (int level, const char *_Nullable str)
int read_gzip (uint8_t *p, unsigned int len, void *arg)
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
static uint8_t *_Nullable const kLexerTestText
Function Documentation
static int lexer_error (int level, const char *_Nullable str) static
Definition at line 30 of file check_lexer_turtle.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 68 of file check_lexer_turtle.c.
References ardp_lexer_create(), ardp_lexer_defaults(), ardp_lexer_destroy(), ardp_lexer_init(), ardp_lexer_process_reader(), ARDP_SUCCESS, ARDP_UNKNOWN, ardp_lexer_config::cb, CRITICAL, die(), is, isnt, lexer_error(), ardp_lexer_config::logging, and read_gzip().
int read_gzip (uint8_t * p, unsigned int len, void * arg)
Definition at line 35 of file check_lexer_turtle.c.
Referenced by main().
Variable Documentation
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 28 of file check_lexer_turtle.c.
uint8_t* _Nullable const kLexerTestText static
Initial value:
= (uint8_t *)
      "  @base <http://example.org/> .\n"
      "  @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
      "  @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n"
      "  @prefix foaf: <http://xmlns.com/foaf/0.1/> .\n"
      "  @prefix rel: <http://www.perceive.net/schemas/relationship/> . \n"
      ""
      "  <#green-goblin>\n"
      "      rel:enemyOf <#spiderman> ;\n"
      "      a foaf:Person ;    # in the context of the Marvel universe\n"
      "      foaf:name \"Green Goblin\" .\n"
      ""
      "  <#spiderman>\n"
      "      rel:enemyOf <#green-goblin> ;\n"
      "      a foaf:Person ;\n"
      "     foaf:name \'Spiderman\' , \"Человек-паук\"@ru .\n"
      ""
      "  @prefix : <http://example.org/stuff/1.0/> .\n"
      "  (1 -2.0 -3E-1 true false) :p \"w\" ."
      ""
      "  :a :b\n"
      "  [ rdf:first \"apple\";\n"
      "     rdf:rest [ rdf:first \"banana\";\n"
      "     rdf:rest rdf:nil ]\n"
      "  ] ."
Definition at line 41 of file check_lexer_turtle.c.