.TH ARDP 1
.SH NAME
ardp - Another RDF Document parser
.SH SYNOPSIS
.B ardp
[\fB\-f\fR \f dataset.ttl\fR]
[\fB\-b\fR]
.SH DESCRIPTION
.B ardp
Command line tool to parse RDF(1.1) Turtle and N-Triples datasets files and archives.
.SH OPTIONS
.TP
.BR \-f ", " \-\-file=\fIfilename\fR
  File to be opened
.TP
.BR \-b
  Use un-archivation with the read (gzip)
