ARDP: /Developer/school/ardp/tests/check_sequence_free.c File Reference
check_sequence_free.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ardp/rdf.h>
#include <ardp/sequence.h>
Functions
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Function Documentation
int main (int argc, char ** argv)
Definition at line 10 of file check_sequence_free.c.
References rdf_statement_copy(), rdf_statement_free(), rdf_statement_from_nodes(), rdf_term_from_uri(), sequence_create(), sequence_free(), sequence_push(), and string_create().
Variable Documentation
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 8 of file check_sequence_free.c.