ARDP: /Developer/school/ardp/.ycm_extra_conf.py File Reference
/Developer/school/ardp/.ycm_extra_conf.py File Reference
Functions
def DirectoryOfThisScript ()
def MakeRelativePathsInFlagsAbsolute (flags, working_directory)
def IsHeaderFile (filename)
def GetCompilationInfoForFile (filename)
def FlagsForFile (filename, kwargs)
Variables
list flags
string compilation_database_folder = ''
tuple database = ycm_core.CompilationDatabase(compilation_database_folder)
list SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]
Function Documentation
def DirectoryOfThisScript ()
Definition at line 65 of file .ycm_extra_conf.py.
Referenced by FlagsForFile().
def FlagsForFile (filename, kwargs)
Definition at line 121 of file .ycm_extra_conf.py.
References DirectoryOfThisScript(), GetCompilationInfoForFile(), and MakeRelativePathsInFlagsAbsolute().
def GetCompilationInfoForFile (filename)
Definition at line 103 of file .ycm_extra_conf.py.
References IsHeaderFile().
Referenced by FlagsForFile().
def IsHeaderFile (filename)
Definition at line 98 of file .ycm_extra_conf.py.
Referenced by GetCompilationInfoForFile().
def MakeRelativePathsInFlagsAbsolute (flags, working_directory)
Definition at line 69 of file .ycm_extra_conf.py.
Referenced by FlagsForFile().
Variable Documentation
string compilation_database_folder = ''
Definition at line 56 of file .ycm_extra_conf.py.
database = ycm_core.CompilationDatabase(compilation_database_folder)
Definition at line 59 of file .ycm_extra_conf.py.
list flags
Initial value:
 = [
     '-x',
     'c',
     '-DHAVE_CONFIG_H',
     '-I.',
     '-I../..',
     '-I../../include',
 ]
Definition at line 36 of file .ycm_extra_conf.py.
list SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]
Definition at line 63 of file .ycm_extra_conf.py.