ARDP: /Developer/school/ardp/src/bin/string.test.c File Reference
string.test.c File Reference
#include <assert.h>
#include <string.h>
Functions
bool test_string_addition_with_realloc (void)
void test_string (void)
Function Documentation
void test_string (void)
Definition at line 8 of file string.test.c.
References test_string_addition_with_realloc().
bool test_string_addition_with_realloc (void)
Definition at line 14 of file string.test.c.
References string_append_char(), string_dealloc(), and string_new().
Referenced by test_string().