.TH "_cursor" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cursor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBline\fP"
.br
.ti -1c
.RI "size_t \fBcol\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t col"

.SS "size_t line"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
