.TH "_datatype_sys_t" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_datatype_sys_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8\fP \fB_Nullable\fP \fBlangtag\fP"
.br
.RI "\fIDenotes that the object has langtag\&. \fP"
.ti -1c
.RI "\fButf8\fP \fB_Nullable\fP \fBdatatype\fP"
.br
.RI "\fIDenotes that the object has datatype\&. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fButf8\fP \fB_Nullable\fP datatype"

.PP
Denotes that the object has datatype\&. 
.PP
Referenced by yy_reduce()\&.
.SS "\fButf8\fP \fB_Nullable\fP langtag"

.PP
Denotes that the object has langtag\&. 
.PP
Referenced by yy_reduce()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
