.TH "/Developer/school/ardp/src Directory Reference" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbin\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.in -1c
