.TH "/Developer/school/ardp/src/lib/rdf Directory Reference" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/src/lib/rdf Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrdf_statement\&.c\fP"
.br
.ti -1c
.RI "file \fBrdf_term\&.c\fP"
.br
.RI "\fIImplementation of the \fC\fBrdf_term\fP\fP \fP"
.in -1c
