.TH "/Developer/school/ardp/include/ardp Directory Reference" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/include/ardp Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolor\&.h\fP"
.br
.RI "\fIColor TTY\&. \fP"
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.ti -1c
.RI "file \fBhash\&.h\fP"
.br
.RI "\fIHashing function to choose from in hashmap\&. \fP"
.ti -1c
.RI "file \fBhashmap\&.h\fP"
.br
.ti -1c
.RI "file \fBlexer\&.h\fP"
.br
.ti -1c
.RI "file \fBlexer\&.turtle\&.h\fP"
.br
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.ti -1c
.RI "file \fBrdf\&.h\fP"
.br
.ti -1c
.RI "file \fBrdf\&.uris\&.h\fP"
.br
.ti -1c
.RI "file \fBsequence\&.h\fP"
.br
.ti -1c
.RI "file \fBstring\&.h\fP"
.br
.RI "\fIThe ARDP's 'Fat-pointer' string library\&. \fP"
.ti -1c
.RI "file \fButil\&.h\fP"
.br
.RI "\fIUtilites for the ARDP programme\&. \fP"
.in -1c
