.TH "/Developer/school/ardp/tests Directory Reference" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/tests Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcheck_ardp_color\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_hashmap_create\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_hashmap_get\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_hashmap_push\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_hashmap_resize\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_lexer_turtle\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_rdf_statement_create\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_rdf_term_copy\&.c\fP"
.br
.RI "\fITest to spot regression in \fBrdf_term\fP implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_rdf_term_create\&.c\fP"
.br
.RI "\fITest to spot regression in \fBrdf_term\fP implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_rdf_term_is\&.c\fP"
.br
.RI "\fITest to spot regression in \fBrdf_term\fP implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_sequence_free\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_string\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_string_append\&.c\fP"
.br
.RI "\fITest to spot regression in string implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_string_append_str\&.c\fP"
.br
.RI "\fITest to spot regression in string implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_string_copy\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_string_create\&.c\fP"
.br
.ti -1c
.RI "file \fBcheck_string_generic_cmp\&.c\fP"
.br
.RI "\fITest to spot regression in string implemenation\&. \fP"
.ti -1c
.RI "file \fBcheck_string_strlen\&.c\fP"
.br
.RI "\fITest to spot regression in string implemenation\&. \fP"
.in -1c
