.TH "_token" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_token \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstruct\fP \fBcursor\fP \fBpos\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBint\fP \fBi\fP"
.br
.ti -1c
.RI "   double \fBdbl\fP"
.br
.ti -1c
.RI "   \fButf8\fP \fBstr\fP"
.br
.ti -1c
.RI "   char \fBchr\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char chr"

.SS "double dbl"

.SS "\fBint\fP i"

.SS "\fBstruct\fP \fBcursor\fP pos"

.SS "\fButf8\fP str"

.SS "union { \&.\&.\&. }   value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
