.TH "ardp_lexer_config.logging" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ardp_lexer_config.logging \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int(* \fB_Nullable\fP )(int level, const char *_Nullable str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file lexer\&.h\&.
.SH "Field Documentation"
.PP 
.SS ""

.SS ""


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
