.TH "ardp_parser_s" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ardp_parser_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8\fP \fBstring\fP"
.br
.ti -1c
.RI "\fBint\fP \fBline\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfinished\fP"
.br
.ti -1c
.RI "ardp_reader \fBreader\fP"
.br
.ti -1c
.RI "\fBvar\fP \fBreader_arg\fP"
.br
.ti -1c
.RI "ardp_handler \fBhandler\fP"
.br
.ti -1c
.RI "\fBvar\fP \fBhandler_arg\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBint\fP cs"

.SS "\fBint\fP finished"

.SS "ardp_handler handler"

.SS "\fBvar\fP handler_arg"

.SS "\fBint\fP line"

.SS "ardp_reader reader"

.SS "\fBvar\fP reader_arg"

.SS "\fButf8\fP string"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
