.TH "ardp_lexer_config.cb" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ardp_lexer_config.cb \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(^ \fB_Nullable\fP )(int type, \fButf8\fP _Nullable value, size_t line, size_t col)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file lexer\&.h\&.
.SH "Field Documentation"
.PP 
.SS ""


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
