.TH "cb" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cb \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SH "Detailed Description"
.PP 
Groups together the callback functions\&.
.PP
\fBNote:\fP
.RS 4
Those functions are part of the object and are linked after creation of the object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
