.TH "/Developer/school/ardp/tests/check_ardp_color.c" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/tests/check_ardp_color.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ardp/color\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcolor_stdout_is_tty\fP = -1"
.br
.RI "\fIGenerally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 7 of file check_ardp_color\&.c\&.
.PP
References ARDP_COLOR_NORMAL, ardp_fprintf(), ardp_fprintf_ln(), and kARDPColorRed\&.
.SH "Variable Documentation"
.PP 
.SS "int color_stdout_is_tty = -1"

.PP
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection\&. 
.PP
Definition at line 5 of file check_ardp_color\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
