.TH "/Developer/school/ardp/tests/check_string_append.c" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/tests/check_string_append.c \- Test to spot regression in string implemenation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcolor_stdout_is_tty\fP = -1"
.br
.RI "\fIGenerally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test to spot regression in string implemenation\&. 

This files tests the function which are supporsed to append string\&. 
.PP
Definition in file \fBcheck_string_append\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 16 of file check_string_append\&.c\&.
.PP
References string_append(), string_copy(), string_create(), and string_dealloc()\&.
.SH "Variable Documentation"
.PP 
.SS "int color_stdout_is_tty = -1"

.PP
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection\&. 
.PP
Definition at line 14 of file check_string_append\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
