.TH "/Developer/school/ardp/build/config.h" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARDP_ON_OSX\fP   1"
.br
.ti -1c
.RI "#define \fBARDP_VERSION_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBARDP_VERSION_MINOR\fP   2"
.br
.ti -1c
.RI "#define \fBARDP_VERSION_PATCH\fP   0"
.br
.ti -1c
.RI "#define \fBARDP_VERSION_STRING\fP   '2\&.2\&.0'"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ISO646_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBBZ2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBZ\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__BOOL\fP   1"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'ardp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'tomas\&.michalek\&.st@vsb\&.cz'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'ardp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'ardp 2\&.2\&.0'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'ardp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '2\&.2\&.0'"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '2\&.2\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARDP_ON_OSX   1"

.PP
Definition at line 5 of file config\&.h\&.
.SS "#define ARDP_VERSION_MAJOR   2"

.PP
Definition at line 14 of file config\&.h\&.
.SS "#define ARDP_VERSION_MINOR   2"

.PP
Definition at line 17 of file config\&.h\&.
.SS "#define ARDP_VERSION_PATCH   0"

.PP
Definition at line 20 of file config\&.h\&.
.SS "#define ARDP_VERSION_STRING   '2\&.2\&.0'"

.PP
Definition at line 23 of file config\&.h\&.
.SS "#define HAVE__BOOL   1"

.PP
Definition at line 79 of file config\&.h\&.
.SS "#define HAVE_INTTYPES_H   1"

.PP
Definition at line 26 of file config\&.h\&.
.SS "#define HAVE_ISO646_H   1"

.PP
Definition at line 29 of file config\&.h\&.
.SS "#define HAVE_LIBBZ2   1"

.PP
Definition at line 32 of file config\&.h\&.
.SS "#define HAVE_LIBZ   1"

.PP
Definition at line 35 of file config\&.h\&.
.SS "#define HAVE_MALLOC   1"

.PP
Definition at line 39 of file config\&.h\&.
.SS "#define HAVE_MEMMOVE   1"

.PP
Definition at line 42 of file config\&.h\&.
.SS "#define HAVE_MEMORY_H   1"

.PP
Definition at line 45 of file config\&.h\&.
.SS "#define HAVE_MEMSET   1"

.PP
Definition at line 48 of file config\&.h\&.
.SS "#define HAVE_REALLOC   1"

.PP
Definition at line 52 of file config\&.h\&.
.SS "#define HAVE_STDINT_H   1"

.PP
Definition at line 55 of file config\&.h\&.
.SS "#define HAVE_STDLIB_H   1"

.PP
Definition at line 58 of file config\&.h\&.
.SS "#define HAVE_STRCASECMP   1"

.PP
Definition at line 61 of file config\&.h\&.
.SS "#define HAVE_STRING_H   1"

.PP
Definition at line 67 of file config\&.h\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Definition at line 64 of file config\&.h\&.
.SS "#define HAVE_SYS_STAT_H   1"

.PP
Definition at line 70 of file config\&.h\&.
.SS "#define HAVE_SYS_TYPES_H   1"

.PP
Definition at line 73 of file config\&.h\&.
.SS "#define HAVE_UNISTD_H   1"

.PP
Definition at line 76 of file config\&.h\&.
.SS "#define PACKAGE   'ardp'"

.PP
Definition at line 82 of file config\&.h\&.
.SS "#define PACKAGE_BUGREPORT   'tomas\&.michalek\&.st@vsb\&.cz'"

.PP
Definition at line 85 of file config\&.h\&.
.SS "#define PACKAGE_NAME   'ardp'"

.PP
Definition at line 88 of file config\&.h\&.
.SS "#define PACKAGE_STRING   'ardp 2\&.2\&.0'"

.PP
Definition at line 91 of file config\&.h\&.
.PP
Referenced by help(), and main()\&.
.SS "#define PACKAGE_TARNAME   'ardp'"

.PP
Definition at line 94 of file config\&.h\&.
.SS "#define PACKAGE_URL   ''"

.PP
Definition at line 97 of file config\&.h\&.
.SS "#define PACKAGE_VERSION   '2\&.2\&.0'"

.PP
Definition at line 100 of file config\&.h\&.
.SS "#define STDC_HEADERS   1"

.PP
Definition at line 103 of file config\&.h\&.
.SS "#define VERSION   '2\&.2\&.0'"

.PP
Definition at line 106 of file config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
