.TH "/Developer/school/ardp/build/doc/html/search/defines_3.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/defines_3.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvar\fP \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBvar\fP searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['colon',['COLON',['\&.\&./turtle__parser_8h\&.html#a8301ee0d0b0055ebb4e8ecc46fadd69e',1,'turtle_parser\&.h']]],
  ['comma',['COMMA',['\&.\&./turtle__parser_8h\&.html#aa2f49001be13949a16a57e6c99ab00ad',1,'turtle_parser\&.h']]]
]
.fi
.PP
Definition at line 1 of file defines_3\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
