.TH "/Developer/school/ardp/build/doc/html/search/enumvalues_c.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/enumvalues_c.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvar\fP \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBvar\fP searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['r_5fcurly',['R_CURLY',['\&.\&./lexer_8turtle_8h\&.html#ac38b3e4c635e7be025ca0fe61e3774efad118184fdd64c2942051be48a16f92f0',1,'lexer\&.turtle\&.h']]],
  ['r_5fround',['R_ROUND',['\&.\&./lexer_8turtle_8h\&.html#ac38b3e4c635e7be025ca0fe61e3774efac5615a7f66bff548a9baa7d048fdb7a8',1,'lexer\&.turtle\&.h']]],
  ['r_5fsquare',['R_SQUARE',['\&.\&./lexer_8turtle_8h\&.html#ac38b3e4c635e7be025ca0fe61e3774efacf977473aa18810118f61c262c7505c2',1,'lexer\&.turtle\&.h']]],
  ['rdf_5fterm_5fblank',['RDF_TERM_BLANK',['\&.\&./rdf_8h\&.html#a034987ef51cf8eb03fe327a1b2ed888ea33b778decc0bc98c9a79f2eda0bb80d4',1,'rdf\&.h']]],
  ['rdf_5fterm_5fcurie',['RDF_TERM_CURIE',['\&.\&./rdf_8h\&.html#a034987ef51cf8eb03fe327a1b2ed888ea0c54c049cbbe63f4267dc8cf36b09a09',1,'rdf\&.h']]],
  ['rdf_5fterm_5fliteral',['RDF_TERM_LITERAL',['\&.\&./rdf_8h\&.html#a034987ef51cf8eb03fe327a1b2ed888ea74ab727b94ede3b9c5726574c52b32c8',1,'rdf\&.h']]],
  ['rdf_5fterm_5funknown',['RDF_TERM_UNKNOWN',['\&.\&./rdf_8h\&.html#a034987ef51cf8eb03fe327a1b2ed888ea3f3c7887641790c64e72b8a89c761c84',1,'rdf\&.h']]],
  ['rdf_5fterm_5furi',['RDF_TERM_URI',['\&.\&./rdf_8h\&.html#a034987ef51cf8eb03fe327a1b2ed888eacc7fc8b708302119a65cadff2178b3c0',1,'rdf\&.h']]],
  ['rdf_5ftype',['RDF_TYPE',['\&.\&./parser_8obj_8c\&.html#a3f9bcd4e29e3cdc55c149985d0d59e0da22b7dc29f6667f52985fe1201753bc0d',1,'parser\&.obj\&.c']]],
  ['ready',['READY',['\&.\&./lexer__mockup_8c\&.html#afadcac5aa76e604c120014ad79a55c9fa6564f2f3e15be06b670547bbcaaf0798',1,'lexer_mockup\&.c']]]
]
.fi
.PP
Definition at line 1 of file enumvalues_c\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
