.TH "/Developer/school/ardp/build/doc/html/search/enums_2.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/enums_2.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvar\fP \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBvar\fP searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['lexer_5ferror',['lexer_error',['\&.\&./lexer_8h\&.html#a51be2a9f9f6653a6997f19ca20274070',1,'lexer\&.h']]],
  ['lexer_5flog_5flevel',['lexer_log_level',['\&.\&./lexer_8h\&.html#a667daa4b51a1f5b1534d558c94cd907d',1,'lexer\&.h']]],
  ['lexer_5fstatus',['lexer_status',['\&.\&./lexer_8h\&.html#ab27b819f9afab7abd01e20bb5b173666',1,'lexer\&.h']]]
]
.fi
.PP
Definition at line 1 of file enums_2\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
