.TH "/Developer/school/ardp/include/ardp/error.h" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/include/ardp/error.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ardp/color\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBardp_error_msg\fP (int lvl, const char *\fB_Nullable\fP domain, const char *\fB_Nonnull\fP desc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void ardp_error_msg (int lvl, const char *\fB_Nullable\fP domain, const char *\fB_Nonnull\fP desc)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 41 of file error\&.h\&.
.PP
References ARDP_COLOR_BLUE, ARDP_COLOR_GREEN, ARDP_COLOR_NORMAL, ARDP_COLOR_RED, ARDP_COLOR_YELLOW, ardp_fprintf(), ERROR, INFO, and WARNING\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
