.TH "/Developer/school/ardp/include/ardp/lexer.turtle.h" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/include/ardp/lexer.turtle.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBturtle_token_type\fP { \fBDOT\fP = 1, \fBPREFIX\fP, \fBCOLON\fP, \fBIRIREF\fP, \fBQNAME\fP, \fBBASE\fP, \fBSPARQL_BASE\fP, \fBSPARQL_PREFIX\fP, \fBSEMICOLON\fP, \fBCOMMA\fP, \fBA\fP, \fBL_SQUARE\fP, \fBR_SQUARE\fP, \fBL_ROUND\fP, \fBR_ROUND\fP, \fBINTEGER_LITERAL\fP, \fBDECIMAL_LITERAL\fP, \fBDOUBLE_LITERAL\fP, \fBLANGTAG\fP, \fBHAT\fP, \fBBOOLEAN_LITERAL\fP, \fBSTRING_LITERAL\fP, \fBBLANK_LITERAL\fP, \fBL_CURLY\fP, \fBR_CURLY\fP, \fBINVALID\fP }"
.br
.RI "\fIEnumerates token types to explicit values for the turtle parsing\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Formalized Turtle and N-Triples specific options and constants for the lexer\&.
.PP
\fBAuthor:\fP
.RS 4
Tomas Michalek <tomas.michalek.st@vsb.cz 
.RE
.PP
\fBDate:\fP
.RS 4
2015 
.RE
.PP

.PP
Definition in file \fBlexer\&.turtle\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBturtle_token_type\fP"

.PP
Enumerates token types to explicit values for the turtle parsing\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDOT \fP\fP
.TP
\fB\fIPREFIX \fP\fP
.TP
\fB\fICOLON \fP\fP
.TP
\fB\fIIRIREF \fP\fP
.TP
\fB\fIQNAME \fP\fP
.TP
\fB\fIBASE \fP\fP
.TP
\fB\fISPARQL_BASE \fP\fP
.TP
\fB\fISPARQL_PREFIX \fP\fP
.TP
\fB\fISEMICOLON \fP\fP
.TP
\fB\fICOMMA \fP\fP
.TP
\fB\fIA \fP\fP
.TP
\fB\fIL_SQUARE \fP\fP
.TP
\fB\fIR_SQUARE \fP\fP
.TP
\fB\fIL_ROUND \fP\fP
.TP
\fB\fIR_ROUND \fP\fP
.TP
\fB\fIINTEGER_LITERAL \fP\fP
.TP
\fB\fIDECIMAL_LITERAL \fP\fP
.TP
\fB\fIDOUBLE_LITERAL \fP\fP
.TP
\fB\fILANGTAG \fP\fP
.TP
\fB\fIHAT \fP\fP
.TP
\fB\fIBOOLEAN_LITERAL \fP\fP
.TP
\fB\fISTRING_LITERAL \fP\fP
.TP
\fB\fIBLANK_LITERAL \fP\fP
.TP
\fB\fIL_CURLY \fP\fP
.TP
\fB\fIR_CURLY \fP\fP
.TP
\fB\fIINVALID \fP\fP
.PP
Definition at line 15 of file lexer\&.turtle\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
