.TH "md___developer_school_ardp_doc_chapter-04-_the-_implementation" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___developer_school_ardp_doc_chapter-04-_the-_implementation \- 4 The Implementation 

.SS "4\&.1 ARDP - Another RDF Document Parser"
.PP
.SS "4\&.2 Program structure"
.PP
.SS "4\&.3 Grand Central Dispatch"
.PP
.SS "4\&.4 Clang toolkit"
.PP
.SS "4\&.4\&.1 clang-format"
.PP
.SS "4\&.4\&.2 clang-analyer"

