.TH "md___developer_school_ardp_doc_parser" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___developer_school_ardp_doc_parser \- parser 
#Parsers
.PP
.SS "What is parser"
.PP
.SS "Composition of parser"
.PP
.SS "Types of parsers"
.PP
.SS "LL parser"
.PP
.SS "LR parser"
.PP
.SS "FSM parser"
.PP
.SS "Tools for creating parsers"
.PP
.SS "Ragel"
.PP
\fCRagel\fP is tool created to simplify creation of \fCFSM\fP type parsers and lexers\&. 
