.TH "parser.cb" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser.cb \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fB_Nullable\fP )(\fButf8\fP _Nullable base)"
.br
.ti -1c
.RI "\fButf8\fP _Nullable(* \fB_Nullable\fP )()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file parser\&.h\&.
.SH "Field Documentation"
.PP 
.SS ""

.SS ""


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
