.TH "Parser" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBint\fP \fBcs\fP"
.br
.ti -1c
.RI "ardp_parser_obj_reader \fBreader\fP"
.br
.ti -1c
.RI "\fBardp_parser_obj_handler\fP \fBhandler\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBint\fP cs"

.SS "\fBardp_parser_obj_handler\fP handler"

.SS "ardp_parser_obj_reader reader"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
