.TH "/Developer/school/ardp/include/ardp/rdf.uris.h" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/include/ardp/rdf.uris.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t *const \fBxsd_uri\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfNil\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfFirst\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfRest\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfBoolean\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfInt\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfFloat\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfDouble\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfLong\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfShort\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfInteger\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfDecimal\fP"
.br
.ti -1c
.RI "uint8_t *const \fBrdfString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines URIs to be used in the parser as per XMLSchema
.PP
\fBAuthor:\fP
.RS 4
Tomas Michalek tomas.michalek.st@vsb.cz 
.RE
.PP
\fBDate:\fP
.RS 4
2016 
.RE
.PP

.PP
Definition in file \fBrdf\&.uris\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t* const rdfBoolean"

.PP
Definition at line 40 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfDecimal"

.PP
Definition at line 47 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfDouble"

.PP
Definition at line 43 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfFirst"

.PP
Definition at line 36 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfFloat"

.PP
Definition at line 42 of file turtle_parser\&.c\&.
.SS "uint8_t* const rdfInt"

.PP
Definition at line 41 of file turtle_parser\&.c\&.
.SS "uint8_t* const rdfInteger"

.PP
Definition at line 46 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfLong"

.PP
Definition at line 44 of file turtle_parser\&.c\&.
.SS "uint8_t* const rdfNil"

.PP
Definition at line 35 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfRest"

.PP
Definition at line 37 of file turtle_parser\&.c\&.
.PP
Referenced by yy_reduce()\&.
.SS "uint8_t* const rdfShort"

.PP
Definition at line 45 of file turtle_parser\&.c\&.
.SS "uint8_t* const rdfString"

.PP
Definition at line 48 of file turtle_parser\&.c\&.
.SS "uint8_t* const xsd_uri"

.PP
Definition at line 33 of file turtle_parser\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
