.TH "/Developer/school/ardp/build/doc/html/search/search.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/search.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBconvertToId\fP (search)"
.br
.ti -1c
.RI "function \fBgetXPos\fP (item)"
.br
.ti -1c
.RI "function \fBgetYPos\fP (item)"
.br
.ti -1c
.RI "function \fBSearchBox\fP (\fBname\fP, resultsPath, inFrame, label)"
.br
.ti -1c
.RI "function \fBSearchResults\fP (\fBname\fP)"
.br
.ti -1c
.RI "function \fBsetKeyActions\fP (elem, action)"
.br
.ti -1c
.RI "function \fBsetClassAttr\fP (elem, attr)"
.br
.ti -1c
.RI "function \fBcreateResults\fP ()"
.br
.ti -1c
.RI "function \fBinit_search\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function convertToId ( search)"

.PP
Definition at line 1 of file search\&.js\&.
.PP
References c\&.
.PP
Referenced by SearchResults()\&.
.SS "function createResults ()"

.PP
Definition at line 722 of file search\&.js\&.
.PP
References c, searchData, setClassAttr(), and setKeyActions()\&.
.SS "function getXPos ( item)"

.PP
Definition at line 24 of file search\&.js\&.
.PP
Referenced by SearchBox()\&.
.SS "function getYPos ( item)"

.PP
Definition at line 38 of file search\&.js\&.
.PP
Referenced by SearchBox()\&.
.SS "function init_search ()"

.PP
Definition at line 777 of file search\&.js\&.
.PP
References indexSectionLabels\&.
.SS "function SearchBox ( name,  resultsPath,  inFrame,  label)"

.PP
Definition at line 59 of file search\&.js\&.
.PP
References getXPos(), getYPos(), if(), indexSectionNames, indexSectionsWithContent, and name\&.
.SS "function SearchResults ( name)"

.PP
Definition at line 404 of file search\&.js\&.
.PP
References convertToId(), and if()\&.
.SS "function setClassAttr ( elem,  attr)"

.PP
Definition at line 716 of file search\&.js\&.
.PP
Referenced by createResults()\&.
.SS "function setKeyActions ( elem,  action)"

.PP
Definition at line 709 of file search\&.js\&.
.PP
Referenced by createResults()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
