.TH "/Developer/school/ardp/src/bin/string.test.c" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/src/bin/string.test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtest_string_addition_with_realloc\fP (void)"
.br
.ti -1c
.RI "void \fBtest_string\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void test_string (void)"

.PP
Definition at line 8 of file string\&.test\&.c\&.
.PP
References test_string_addition_with_realloc()\&.
.SS "bool test_string_addition_with_realloc (void)"

.PP
Definition at line 14 of file string\&.test\&.c\&.
.PP
References string_append_char(), string_dealloc(), and string_new()\&.
.PP
Referenced by test_string()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
