.TH "token" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token \- Holds the single lexical unit and its value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lexer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBint\fP \fBtype\fP"
.br
.RI "\fIEnumerated token type\&. \fP"
.ti -1c
.RI "char *\fB_Nullable\fP \fBlexem\fP"
.br
.RI "\fIActual value of the token (optional) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Holds the single lexical unit and its value\&. 

: Geared to be Turtle token type - needs to be generalized\&. 
.SH "Field Documentation"
.PP 
.SS "char* \fB_Nullable\fP lexem"

.PP
Actual value of the token (optional) 
.SS "\fBint\fP type"

.PP
Enumerated token type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
