.TH "/Developer/school/ardp/src/lib/parsers/turtle_parser.h" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/src/lib/parsers/turtle_parser.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDOT\fP   1"
.br
.ti -1c
.RI "#define \fBPREFIX\fP   2"
.br
.ti -1c
.RI "#define \fBCOLON\fP   3"
.br
.ti -1c
.RI "#define \fBIRIREF\fP   4"
.br
.ti -1c
.RI "#define \fBQNAME\fP   5"
.br
.ti -1c
.RI "#define \fBBASE\fP   6"
.br
.ti -1c
.RI "#define \fBSPARQL_BASE\fP   7"
.br
.ti -1c
.RI "#define \fBSPARQL_PREFIX\fP   8"
.br
.ti -1c
.RI "#define \fBSEMICOLON\fP   9"
.br
.ti -1c
.RI "#define \fBCOMMA\fP   10"
.br
.ti -1c
.RI "#define \fBA\fP   11"
.br
.ti -1c
.RI "#define \fBL_SQUARE\fP   12"
.br
.ti -1c
.RI "#define \fBR_SQUARE\fP   13"
.br
.ti -1c
.RI "#define \fBL_CURLY\fP   14"
.br
.ti -1c
.RI "#define \fBR_CURLY\fP   15"
.br
.ti -1c
.RI "#define \fBINTEGER_LITERAL\fP   16"
.br
.ti -1c
.RI "#define \fBDECIMAL_LITERAL\fP   17"
.br
.ti -1c
.RI "#define \fBDOUBLE_LITERAL\fP   18"
.br
.ti -1c
.RI "#define \fBLANGTAG\fP   19"
.br
.ti -1c
.RI "#define \fBHAT\fP   20"
.br
.ti -1c
.RI "#define \fBBOOLEAN_LITERAL\fP   21"
.br
.ti -1c
.RI "#define \fBSTRING_LITERAL\fP   22"
.br
.ti -1c
.RI "#define \fBBLANK_LITERAL\fP   23"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define A   11"

.PP
Definition at line 11 of file turtle_parser\&.h\&.
.SS "#define BASE   6"

.PP
Definition at line 6 of file turtle_parser\&.h\&.
.SS "#define BLANK_LITERAL   23"

.PP
Definition at line 23 of file turtle_parser\&.h\&.
.SS "#define BOOLEAN_LITERAL   21"

.PP
Definition at line 21 of file turtle_parser\&.h\&.
.SS "#define COLON   3"

.PP
Definition at line 3 of file turtle_parser\&.h\&.
.SS "#define COMMA   10"

.PP
Definition at line 10 of file turtle_parser\&.h\&.
.SS "#define DECIMAL_LITERAL   17"

.PP
Definition at line 17 of file turtle_parser\&.h\&.
.SS "#define DOT   1"

.PP
Definition at line 1 of file turtle_parser\&.h\&.
.SS "#define DOUBLE_LITERAL   18"

.PP
Definition at line 18 of file turtle_parser\&.h\&.
.SS "#define HAT   20"

.PP
Definition at line 20 of file turtle_parser\&.h\&.
.SS "#define INTEGER_LITERAL   16"

.PP
Definition at line 16 of file turtle_parser\&.h\&.
.SS "#define IRIREF   4"

.PP
Definition at line 4 of file turtle_parser\&.h\&.
.SS "#define L_CURLY   14"

.PP
Definition at line 14 of file turtle_parser\&.h\&.
.SS "#define L_SQUARE   12"

.PP
Definition at line 12 of file turtle_parser\&.h\&.
.SS "#define LANGTAG   19"

.PP
Definition at line 19 of file turtle_parser\&.h\&.
.SS "#define PREFIX   2"

.PP
Definition at line 2 of file turtle_parser\&.h\&.
.SS "#define QNAME   5"

.PP
Definition at line 5 of file turtle_parser\&.h\&.
.SS "#define R_CURLY   15"

.PP
Definition at line 15 of file turtle_parser\&.h\&.
.SS "#define R_SQUARE   13"

.PP
Definition at line 13 of file turtle_parser\&.h\&.
.SS "#define SEMICOLON   9"

.PP
Definition at line 9 of file turtle_parser\&.h\&.
.SS "#define SPARQL_BASE   7"

.PP
Definition at line 7 of file turtle_parser\&.h\&.
.SS "#define SPARQL_PREFIX   8"

.PP
Definition at line 8 of file turtle_parser\&.h\&.
.SS "#define STRING_LITERAL   22"

.PP
Definition at line 22 of file turtle_parser\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
