.TH "/Developer/school/ardp/build/doc/html/search/typedefs_5.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/typedefs_5.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvar\fP \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBvar\fP searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['sequence_5ferror_5fhandler',['sequence_error_handler',['\&.\&./sequence_8h\&.html#a74e475374ec216167c7148e268ab70cc',1,'sequence\&.h']]],
  ['sequence_5ffree_5fhandler',['sequence_free_handler',['\&.\&./sequence_8h\&.html#a9126fc23e6308b5767446ab80ef7c602',1,'sequence\&.h']]],
  ['sequence_5fprint_5fhandler',['sequence_print_handler',['\&.\&./sequence_8h\&.html#a57a151d55b0b683897a37570a5d3c9a8',1,'sequence\&.h']]]
]
.fi
.PP
Definition at line 1 of file typedefs_5\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
