.TH "/Developer/school/ardp/build/doc/html/search/variables_13.js" 3 "Tue Apr 19 2016" "Version 2.1.3" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Developer/school/ardp/build/doc/html/search/variables_13.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvar\fP \fBsearchData\fP"
.br
.ti -1c
.RI "\fBparser\fP \fBc\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBparser\fP c"

.PP
Definition at line 4 of file variables_13\&.js\&.
.SS "\fBvar\fP searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['uri',['uri',['\&.\&./unionrdf__term__value\&.html#a844f14e39e917b71f62434169b146f84',1,'rdf_term_value::uri()'],['\&.\&./parser_8c\&.html#aebc85eac7aefe772e942d5f583162285',1,'uri():&#160
.fi
.PP
Definition at line 1 of file variables_13\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
