.TH "yyStackEntry" 3 "Tue Apr 26 2016" "Version 2.2.1" "ARDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyStackEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "YYACTIONTYPE \fBstateno\fP"
.br
.ti -1c
.RI "YYCODETYPE \fBmajor\fP"
.br
.ti -1c
.RI "\fBYYMINORTYPE\fP \fBminor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 278 of file turtle_parser\&.c\&.
.SH "Field Documentation"
.PP 
.SS "YYCODETYPE major"

.PP
Definition at line 280 of file turtle_parser\&.c\&.
.SS "\fBYYMINORTYPE\fP minor"

.PP
Definition at line 282 of file turtle_parser\&.c\&.
.SS "YYACTIONTYPE stateno"

.PP
Definition at line 279 of file turtle_parser\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARDP from the source code\&.
