ARDP: /Developer/school/ardp/include/ardp/rdf.h File Reference
rdf.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>
#include <ctype.h>
#include <stdarg.h>
#include "util.h"
Data Structures
struct rdf_term_literal_value
union rdf_term_value
struct rdf_term
struct rdf_statement
Enumerations
enum rdf_term_type {
RDF_TERM_UNKNOWN, RDF_TERM_URI, RDF_TERM_CURIE, RDF_TERM_BLANK,
RDF_TERM_LITERAL
}
Denotes type of the RDF term.
Functions
struct rdf_term * rdf_term_from_uri (utf8 uri)
struct rdf_term * rdf_term_from_curie (utf8 uri)
struct rdf_term * rdf_term_from_blank (utf8 blank)
struct rdf_term * rdf_term_from_literal (utf8 literal, utf8 lang, utf8 datatype)
struct rdf_term * rdf_term_copy (struct rdf_term *t)
static int term_is_uri (struct rdf_term *t)
static int term_is_curie (struct rdf_term *t)
static int term_is_blank (struct rdf_term *t)
static int term_is_literal (struct rdf_term *t)
void rdf_term_free (struct rdf_term *t)
int rdf_term_equals (const struct rdf_term *a, const struct rdf_term *b)
int rdf_term_compare (const struct rdf_term *a, const struct rdf_term *b)
struct rdf_statement * rdf_statement_create (void)
Create new empty RDF statement.
struct rdf_statement * rdf_statement_from_nodes (struct rdf_term *subject, struct rdf_term *predicate, struct rdf_term *object, struct rdf_term *graph)
void rdf_statement_zero (struct rdf_statement *s)
struct rdf_statement * rdf_statement_copy (struct rdf_statement *s)
void rdf_statement_clear (struct rdf_statement *s)
void rdf_statement_free (struct rdf_statement *s)
int rdf_statement_compare (struct rdf_statement *a, struct rdf_statement *b)
int rdf_statement_equals (struct rdf_statement *a, struct rdf_statement *b)
Detailed Description
This file describes the data types specified in #RDF_term.
Definition in file rdf.h.
Data Structure Documentation
struct rdf_term_literal_value
Note
Literal can have either datatype of language. But one or another needs to be set
Definition at line 55 of file rdf.h.
Data Fields
utf8 datatype Datatype of the string.
utf8 language Language of the string.
utf8 string String value of the literal.
union rdf_term_value
Opaque type for the literals.
Definition at line 75 of file rdf.h.
Data Fields
utf8 blank
struct rdf_term_literal_value literal
utf8 uri
struct rdf_term
Definition at line 81 of file rdf.h.
Data Fields
enum rdf_term_type type
union rdf_term_value value
struct rdf_statement
Definition at line 86 of file rdf.h.
Data Fields
struct rdf_term * graph
struct rdf_term * object
struct rdf_term * predicate
struct rdf_term * subject
Enumeration Type Documentation
enum rdf_term_type
Denotes type of the RDF term.
Note
Specifies subset of operations on 'union'
Enumerator
RDF_TERM_UNKNOWN
RDF_TERM_URI
RDF_TERM_CURIE
RDF_TERM_BLANK
RDF_TERM_LITERAL
Definition at line 41 of file rdf.h.
Function Documentation
void rdf_statement_clear (struct rdf_statement * s)
Definition at line 67 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_free(), and rdf_statement::subject.
Referenced by rdf_statement_free().
int rdf_statement_compare (struct rdf_statement * a, struct rdf_statement * b)
Definition at line 89 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_compare(), and rdf_statement::subject.
struct rdf_statement* rdf_statement_copy (struct rdf_statement * s)
Definition at line 42 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_statement_create(), rdf_term_copy(), and rdf_statement::subject.
Referenced by main().
rdf_statement_create (void)
Create new empty RDF statement.
Returns
Statement, NULL on error.
Definition at line 12 of file rdf_statement.c.
Referenced by rdf_statement_copy(), and rdf_statement_from_nodes().
int rdf_statement_equals (struct rdf_statement * a, struct rdf_statement * b)
Definition at line 119 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_equals(), and rdf_statement::subject.
void rdf_statement_free (struct rdf_statement * s)
Definition at line 79 of file rdf_statement.c.
References rdf_statement_clear().
Referenced by main(), and yy_reduce().
struct rdf_statement* rdf_statement_from_nodes (struct rdf_term * subject, struct rdf_term * predicate, struct rdf_term * object, struct rdf_term * graph)
Definition at line 18 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_statement_create(), rdf_term_free(), and rdf_statement::subject.
Referenced by main(), and yy_reduce().
void rdf_statement_zero (struct rdf_statement * s)
Definition at line 61 of file rdf_statement.c.
int rdf_term_compare (const struct rdf_term * a, const struct rdf_term * b)
Definition at line 232 of file rdf_term.c.
References RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, and rdf_term::type.
Referenced by rdf_statement_compare().
struct rdf_term* rdf_term_copy (struct rdf_term * t)
Definition at line 89 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_copy(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), rdf_statement_copy(), and yy_reduce().
int rdf_term_equals (const struct rdf_term * a, const struct rdf_term * b)
Definition at line 162 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_generic_cmp(), string_strlen(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by rdf_statement_equals().
void rdf_term_free (struct rdf_term * t)
Definition at line 128 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_dealloc(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), rdf_statement_clear(), rdf_statement_from_nodes(), yy_destructor(), and yy_reduce().
struct rdf_term* rdf_term_from_blank (utf8 blank)
Definition at line 73 of file rdf_term.c.
References rdf_term_value::blank, RDF_TERM_BLANK, string_copy(), rdf_term::type, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_curie (utf8 uri)
Definition at line 37 of file rdf_term.c.
References RDF_TERM_CURIE, string_copy(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_literal (utf8 literal, utf8 lang, utf8 datatype)
Definition at line 52 of file rdf_term.c.
References rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_LITERAL, rdf_term_literal_value::string, string_copy(), rdf_term::type, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_uri (utf8 uri)
Definition at line 18 of file rdf_term.c.
References RDF_TERM_URI, string_copy(), string_create_n(), string_strlen(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), and yy_reduce().
static int term_is_blank (struct rdf_term * t) inline static
Definition at line 177 of file rdf.h.
References RDF_TERM_BLANK.
Referenced by main().
static int term_is_curie (struct rdf_term * t) inline static
Definition at line 166 of file rdf.h.
References RDF_TERM_CURIE.
Referenced by expand_curie(), and main().
static int term_is_literal (struct rdf_term * t) inline static
Definition at line 188 of file rdf.h.
References RDF_TERM_LITERAL.
Referenced by main().
static int term_is_uri (struct rdf_term * t) inline static
Definition at line 155 of file rdf.h.
References RDF_TERM_URI.
Referenced by expand_relative_uri(), main(), and uri_has_scheme().