ARDP: /Developer/school/ardp/tests/check_rdf_statement_create.c File Reference
check_rdf_statement_create.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ardp/rdf.h>
Functions
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Function Documentation
int main (int argc, char ** argv)
Definition at line 17 of file check_rdf_statement_create.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_statement_free(), rdf_statement_from_nodes(), rdf_term_from_blank(), rdf_term_from_curie(), rdf_term_from_literal(), rdf_term_from_uri(), string_create(), and rdf_statement::subject.
Variable Documentation
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 15 of file check_rdf_statement_create.c.