ARDP: /Developer/school/ardp/src/lib/parsers/turtle_parser.c File Reference
turtle_parser.c File Reference
#include <stdio.h>
#include <assert.h>
#include <stddef.h>
#include <stdlib.h>
#include <errno.h>
#include <ardp/rdf.h>
#include <ardp/string.h>
#include <ardp/sequence.h>
#include <ardp/lexer.h>
#include <ardp/util.h>
#include <ardp/parser.h>
Data Structures
union YYMINORTYPE
struct yyStackEntry
struct yyParser
Macros
#define YYMALLOCARGTYPE u64
#define YYERROR
#define XSD "xsd:"
#define INTERFACE 1
#define YYCODETYPE unsigned char
#define YYNOCODE 58
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE void*
#define YYSTACKDEPTH 100
#define ParseARG_SDECL struct parser* p ;
#define ParseARG_PDECL , struct parser* p
#define ParseARG_FETCH struct parser* p = yypParser->p
#define ParseARG_STORE yypParser->p = p
#define YYNSTATE 80
#define YYNRULE 60
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
#define yytestcase(X)
#define YY_SHIFT_USE_DFLT (-1)
#define YY_SHIFT_MAX 29
#define YY_REDUCE_USE_DFLT (-32)
#define YY_REDUCE_MAX 15
#define YY_SZ_ACTTAB (int)(sizeof(yy_action)/sizeof(yy_action[0]))
#define TOKEN (yyminor.yy0)
Functions
void ParseTrace (FILE *TraceFILE, char *zTracePrompt)
void * ParseAlloc (void *(*mallocProc)(size_t))
static void yy_destructor (yyParser *yypParser, YYCODETYPE yymajor, YYMINORTYPE *yypminor)
static int yy_pop_parser_stack (yyParser *pParser)
void ParseFree (void *p, void(*freeProc)(void *))
static int yy_find_shift_action (yyParser *pParser, YYCODETYPE iLookAhead)
static int yy_find_reduce_action (int stateno, YYCODETYPE iLookAhead)
static void yyStackOverflow (yyParser *yypParser, YYMINORTYPE *yypMinor)
static void yy_shift (yyParser *yypParser, int yyNewState, int yyMajor, YYMINORTYPE *yypMinor)
static void yy_accept (yyParser *)
static void yy_reduce (yyParser *yypParser, int yyruleno)
static void yy_parse_failed (yyParser *yypParser)
static void yy_syntax_error (yyParser *yypParser, int yymajor, YYMINORTYPE yyminor)
void Parse (void *yyp, int yymajor, ParseTOKENTYPE yyminorParseARG_PDECL)
Variables
const uint8_t *const xsd_uri = (uint8_t *) "http://www.w3.org/2001/XMLSchema#"
const uint8_t *const rdfNil = (uint8_t *) "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"
const uint8_t *const rdfFirst = (uint8_t *) "http://www.w3.org/2001/XMLSchema#First"
const uint8_t *const rdfRest = (uint8_t *) "http://www.w3.org/2001/XMLSchema#Rest"
const uint8_t *const rdfBoolean = (uint8_t*) XSD"Boolean"
const uint8_t *const rdfInt = (uint8_t*) XSD"int"
const uint8_t *const rdfFloat = (uint8_t*) XSD"float"
const uint8_t *const rdfDouble = (uint8_t*) XSD"double"
const uint8_t *const rdfLong = (uint8_t*) XSD"long"
const uint8_t *const rdfShort = (uint8_t*) XSD"short"
const uint8_t *const rdfInteger = (uint8_t*) XSD"integer"
const uint8_t *const rdfDecimal = (uint8_t*) XSD"decimal"
const uint8_t *const rdfString = (uint8_t*) XSD"string"
const uint8_t *const rdfType = (uint8_t *) "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
static const YYMINORTYPE yyzerominor = { 0 }
static const YYACTIONTYPE yy_action []
static const YYCODETYPE yy_lookahead []
static const signed char yy_shift_ofst []
static const signed char yy_reduce_ofst []
static const YYACTIONTYPE yy_default []
static FILE * yyTraceFILE = 0
static char * yyTracePrompt = 0
static const char *const yyTokenName []
static const char *const yyRuleName []
struct {
YYCODETYPE lhs
unsigned char nrhs
} yyRuleInfo []
Data Structure Documentation
union YYMINORTYPE
Definition at line 105 of file turtle_parser.c.
Data Fields
ParseTOKENTYPE yy0
utf8 yy2
struct sequence * yy33
struct rdf_term * yy79
datatype_sys_t * yy8
int yyinit
struct yyStackEntry
Definition at line 278 of file turtle_parser.c.
Data Fields
YYCODETYPE major
YYMINORTYPE minor
YYACTIONTYPE stateno
struct yyParser
Definition at line 289 of file turtle_parser.c.
Data Fields
int yyerrcnt
int yyidx
ParseARG_SDECL yyStackEntry yystack[YYSTACKDEPTH]
Macro Definition Documentation
#define INTERFACE 1
Definition at line 65 of file turtle_parser.c.
#define ParseARG_FETCH struct parser* p = yypParser->p
Definition at line 118 of file turtle_parser.c.
Referenced by yy_accept(), yy_destructor(), yy_parse_failed(), yy_reduce(), yy_syntax_error(), and yyStackOverflow().
#define ParseARG_PDECL , struct parser* p
Definition at line 117 of file turtle_parser.c.
#define ParseARG_SDECL struct parser* p ;
Definition at line 116 of file turtle_parser.c.
#define ParseARG_STORE yypParser->p = p
Definition at line 119 of file turtle_parser.c.
Referenced by Parse(), yy_accept(), yy_parse_failed(), yy_syntax_error(), and yyStackOverflow().
#define ParseTOKENTYPE void*
Definition at line 104 of file turtle_parser.c.
#define TOKEN (yyminor.yy0)
Referenced by yy_syntax_error().
#define XSD "xsd:"
Definition at line 39 of file turtle_parser.c.
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
Definition at line 123 of file turtle_parser.c.
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
Definition at line 124 of file turtle_parser.c.
Referenced by Parse().
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
Definition at line 122 of file turtle_parser.c.
#define YY_REDUCE_MAX 15
Definition at line 234 of file turtle_parser.c.
Referenced by yy_find_reduce_action().
#define YY_REDUCE_USE_DFLT (-32)
Definition at line 233 of file turtle_parser.c.
Referenced by yy_find_reduce_action().
#define YY_SHIFT_MAX 29
Definition at line 227 of file turtle_parser.c.
Referenced by yy_find_shift_action().
#define YY_SHIFT_USE_DFLT (-1)
Definition at line 226 of file turtle_parser.c.
Referenced by yy_find_shift_action().
#define YY_SZ_ACTTAB (int)(sizeof(yy_action)/sizeof(yy_action[0]))
Definition at line 249 of file turtle_parser.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YYACTIONTYPE unsigned char
Definition at line 103 of file turtle_parser.c.
Referenced by yy_reduce(), and yy_shift().
#define YYCODETYPE unsigned char
Definition at line 101 of file turtle_parser.c.
Referenced by Parse(), yy_find_shift_action(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), and yy_syntax_error().
#define YYERROR
Value:
do {                                                               \
                        ardp_fprintf(stderr,                                       \
                                     kARDPColorMagenta,                            \
                                     "\n[parser error] on line: %lu\n\n", p->stats.line);   \
                        p->stats.n_errors++;                                       \
                }while(0)
Definition at line 26 of file turtle_parser.c.
Referenced by yy_reduce().
#define YYMALLOCARGTYPE u64
Definition at line 24 of file turtle_parser.c.
#define YYNOCODE 58
Definition at line 102 of file turtle_parser.c.
Referenced by Parse(), yy_find_reduce_action(), and yy_find_shift_action().
#define YYNRULE 60
Definition at line 121 of file turtle_parser.c.
Referenced by Parse(), yy_reduce(), and yy_syntax_error().
#define YYNSTATE 80
Definition at line 120 of file turtle_parser.c.
Referenced by Parse(), yy_reduce(), and yy_syntax_error().
#define YYSTACKDEPTH 100
Definition at line 114 of file turtle_parser.c.
Referenced by yy_shift().
#define yytestcase (X)
Definition at line 139 of file turtle_parser.c.
Referenced by yy_reduce().
Function Documentation
void Parse (void * yyp, int yymajor, ParseTOKENTYPE yyminor ParseARG_PDECL)
Definition at line 1737 of file turtle_parser.c.
References yyStackEntry::major, ParseARG_STORE, yyStackEntry::stateno, YYMINORTYPE::yy0, yy_destructor(), YY_ERROR_ACTION, yy_find_reduce_action(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), yy_syntax_error(), YYCODETYPE, yyParser::yyerrcnt, yyParser::yyidx, YYNOCODE, YYNRULE, YYNSTATE, yyParser::yystack, yyStackOverflow(), yyTokenName, yyTraceFILE, yyTracePrompt, and yyzerominor.
Referenced by ardp_parser_exec(), and ardp_parser_finish().
void* ParseAlloc (void *(*)(size_t) mallocProc)
Definition at line 462 of file turtle_parser.c.
References yyParser::yyidx, and yyParser::yystack.
Referenced by ardp_parser_create().
void ParseFree (void * p, void(*)(void *) freeProc)
Definition at line 619 of file turtle_parser.c.
References yy_pop_parser_stack(), yyParser::yyidx, and yyParser::yystack.
Referenced by ardp_parser_destroy().
void ParseTrace (FILE * TraceFILE, char * zTracePrompt)
Definition at line 329 of file turtle_parser.c.
References yyTraceFILE, and yyTracePrompt.
Referenced by ardp_parser_trace().
static void yy_accept (yyParser * yypParser) static
Definition at line 1699 of file turtle_parser.c.
References ParseARG_FETCH, ParseARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by yy_reduce().
static void yy_destructor (yyParser * yypParser, YYCODETYPE yymajor, YYMINORTYPE * yypminor) static
Definition at line 484 of file turtle_parser.c.
References ParseARG_FETCH, rdf_term_free(), sequence_free(), string_dealloc(), YYMINORTYPE::yy0, YYMINORTYPE::yy2, YYMINORTYPE::yy33, YYMINORTYPE::yy79, and YYMINORTYPE::yy8.
Referenced by Parse(), yy_pop_parser_stack(), and yy_reduce().
static int yy_find_reduce_action (int stateno, YYCODETYPE iLookAhead) static
Definition at line 706 of file turtle_parser.c.
References yy_action, yy_default, yy_lookahead, YY_REDUCE_MAX, yy_reduce_ofst, YY_REDUCE_USE_DFLT, YY_SZ_ACTTAB, and YYNOCODE.
Referenced by Parse(), and yy_reduce().
static int yy_find_shift_action (yyParser * pParser, YYCODETYPE iLookAhead) static
Definition at line 650 of file turtle_parser.c.
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_SHIFT_MAX, yy_shift_ofst, YY_SHIFT_USE_DFLT, YY_SZ_ACTTAB, YYCODETYPE, yyParser::yyidx, YYNOCODE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), and yy_syntax_error().
static void yy_parse_failed (yyParser * yypParser) static
Definition at line 1648 of file turtle_parser.c.
References ardp_fprintf(), kARDPColorMagenta, ParseARG_FETCH, ParseARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by Parse().
static int yy_pop_parser_stack (yyParser * pParser) static
Definition at line 589 of file turtle_parser.c.
References yyStackEntry::major, yyStackEntry::minor, yy_destructor(), YYCODETYPE, yyParser::yyidx, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), ParseFree(), yy_accept(), yy_parse_failed(), and yyStackOverflow().
static void yy_reduce (yyParser * yypParser, int yyruleno) static
Definition at line 875 of file turtle_parser.c.
References datatype_sys_t::datatype, datatype_sys_t::langtag, yyStackEntry::major, yyStackEntry::minor, rdf_statement::object, ParseARG_FETCH, rdf_statement::predicate, rdf_statement_free(), rdf_statement_from_nodes(), rdf_term_copy(), rdf_term_free(), rdf_term_from_blank(), rdf_term_from_curie(), rdf_term_from_literal(), rdf_term_from_uri(), RDF_TERM_URI, rdfBoolean, rdfDecimal, rdfDouble, rdfFirst, rdfInteger, rdfNil, rdfRest, rdfType, sequence_create(), sequence_free(), sequence_get_at(), sequence_push(), sequence_shift(), sequence_size(), sequence_unshift(), yyStackEntry::stateno, string_copy(), string_create(), string_create_n(), string_dealloc(), rdf_statement::subject, rdf_term::type, rdf_term_value::uri, rdf_term::value, YYMINORTYPE::yy0, YYMINORTYPE::yy2, YYMINORTYPE::yy33, YYMINORTYPE::yy79, YYMINORTYPE::yy8, yy_accept(), yy_destructor(), yy_find_reduce_action(), yy_shift(), YYACTIONTYPE, YYCODETYPE, YYERROR, yyParser::yyidx, YYNRULE, YYNSTATE, yyRuleInfo, yyRuleName, yyParser::yystack, yytestcase, yyTraceFILE, yyTracePrompt, and yyzerominor.
Referenced by Parse().
static void yy_shift (yyParser * yypParser, int yyNewState, int yyMajor, YYMINORTYPE * yypMinor) static
Definition at line 757 of file turtle_parser.c.
References yyStackEntry::major, yyStackEntry::minor, yyStackEntry::stateno, YYACTIONTYPE, YYCODETYPE, yyParser::yyidx, yyParser::yystack, YYSTACKDEPTH, yyStackOverflow(), yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), and yy_reduce().
static void yy_syntax_error (yyParser * yypParser, int yymajor, YYMINORTYPE yyminor) static
Definition at line 1672 of file turtle_parser.c.
References ardp_fprintf(), kARDPColorBoldMagenta, kARDPColorMagenta, ParseARG_FETCH, ParseARG_STORE, TOKEN, yy_find_shift_action(), YYCODETYPE, YYNRULE, YYNSTATE, and yyTokenName.
Referenced by Parse().
static void yyStackOverflow (yyParser * yypParser, YYMINORTYPE * yypMinor) static
Definition at line 736 of file turtle_parser.c.
References ardp_fprintf(), kARDPColorMagenta, ParseARG_FETCH, ParseARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), and yy_shift().
Variable Documentation
const uint8_t* const rdfBoolean = (uint8_t*) XSD"Boolean"
Definition at line 40 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfDecimal = (uint8_t*) XSD"decimal"
Definition at line 47 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfDouble = (uint8_t*) XSD"double"
Definition at line 43 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfFirst = (uint8_t *) "http://www.w3.org/2001/XMLSchema#First"
Definition at line 36 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfFloat = (uint8_t*) XSD"float"
Definition at line 42 of file turtle_parser.c.
const uint8_t* const rdfInt = (uint8_t*) XSD"int"
Definition at line 41 of file turtle_parser.c.
const uint8_t* const rdfInteger = (uint8_t*) XSD"integer"
Definition at line 46 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfLong = (uint8_t*) XSD"long"
Definition at line 44 of file turtle_parser.c.
const uint8_t* const rdfNil = (uint8_t *) "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"
Definition at line 35 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfRest = (uint8_t *) "http://www.w3.org/2001/XMLSchema#Rest"
Definition at line 37 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const rdfShort = (uint8_t*) XSD"short"
Definition at line 45 of file turtle_parser.c.
const uint8_t* const rdfString = (uint8_t*) XSD"string"
Definition at line 48 of file turtle_parser.c.
const uint8_t* const rdfType = (uint8_t *) "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
Definition at line 50 of file turtle_parser.c.
Referenced by yy_reduce().
const uint8_t* const xsd_uri = (uint8_t *) "http://www.w3.org/2001/XMLSchema#"
Definition at line 33 of file turtle_parser.c.
const YYACTIONTYPE yy_action[] static
Initial value:
= {
     52,   53,   21,   55,   56,   57,   58,    8,   54,    6,
     31,   32,   61,   48,   42,   47,    2,   78,   49,   50,
     51,   72,   77,   79,   13,   31,   32,   15,   66,   46,
     69,   70,   71,   73,   74,   75,   76,   72,   10,    9,
     67,   46,   22,   15,   24,   12,   69,   70,   71,   73,
     74,   75,   76,   63,   10,   72,    3,   46,   20,   59,
     28,   68,   77,   79,   69,   70,   71,   73,   74,   75,
     76,   18,   10,   31,   32,   46,   41,   11,  141,    1,
      4,    7,   27,   14,   34,   36,   37,   38,   72,   23,
     43,   44,   45,   30,   35,   39,   40,   69,   70,   71,
     73,   74,   75,   76,    5,   10,   60,   19,   46,   80,
     64,   17,   62,   31,   32,   25,   29,   16,  142,   26,
    142,    7,    2,   14,   31,   32,   31,   32,   77,   79,
    142,   78,   45,   33,    7,  142,   14,  142,   36,   37,
     38,  142,  142,   43,   44,   45,  142,   65,  142,  142,
      2,  142,  142,  142,  142,  142,   77,   79,
}
Definition at line 190 of file turtle_parser.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const YYACTIONTYPE yy_default[] static
Initial value:
= {
     82,  140,  140,  140,  140,  140,   98,  140,  140,  103,
    130,  140,   99,  101,  124,  106,  140,  140,  140,  140,
    140,  140,  140,  104,  140,  140,  140,  140,  140,  140,
    121,  135,  136,  139,  122,  123,  125,  126,  127,  128,
    129,  131,  132,  133,  134,  137,  138,   96,   97,  109,
    110,  111,   81,   83,   84,   85,   86,   87,   88,   89,
     90,   91,   92,   93,   94,   95,  100,  102,  105,  113,
    114,  115,  116,  117,  118,  119,  120,  107,  108,  112,
}
Definition at line 239 of file turtle_parser.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const YYCODETYPE yy_lookahead[] static
Initial value:
= {
     27,   28,   29,   30,   31,   32,   33,   34,    1,   36,
      4,    5,    1,   35,   45,   37,   38,   11,   45,   46,
     47,   36,   44,   45,   39,    4,    5,   42,   41,   56,
     45,   46,   47,   48,   49,   50,   51,   36,   53,    9,
     39,   56,    3,   42,    5,   40,   45,   46,   47,   48,
     49,   50,   51,    4,   53,   36,   38,   56,    3,    1,
      5,   42,   44,   45,   45,   46,   47,   48,   49,   50,
     51,    4,   53,    4,    5,   56,   19,   20,   25,   26,
     52,   12,    4,   14,   15,   16,   17,   18,   36,   43,
     21,   22,   23,   13,   42,   54,   55,   45,   46,   47,
     48,   49,   50,   51,   10,   53,    1,    4,   56,    0,
      4,    2,    4,    4,    5,    6,    7,    8,   57,   35,
     57,   12,   38,   14,    4,    5,    4,    5,   44,   45,
     57,   11,   23,   13,   12,   57,   14,   57,   16,   17,
     18,   57,   57,   21,   22,   23,   57,   35,   57,   57,
     38,   57,   57,   57,   57,   57,   44,   45,
}
Definition at line 208 of file turtle_parser.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const signed char yy_reduce_ofst[] static
Initial value:
= {
     53,  -27,  -15,    1,   52,   19,  -22,   84,  112,   18,
     41,  -31,  -13,    5,   28,   46,
}
Definition at line 235 of file turtle_parser.c.
Referenced by yy_find_reduce_action().
const signed char yy_shift_ofst[] static
Initial value:
= {
     -1,  109,  122,  122,   69,  122,    6,  120,    6,    6,
     57,   21,   30,   -1,   -1,   -1,   55,   39,   11,   58,
     49,    7,  103,   94,   78,   67,   80,  105,  106,  108,
}
Definition at line 228 of file turtle_parser.c.
Referenced by yy_find_shift_action().
const { ... } yyRuleInfo[]
Referenced by yy_reduce().
const char* const yyRuleName[] static
Definition at line 362 of file turtle_parser.c.
Referenced by yy_reduce().
const char* const yyTokenName[] static
Initial value:
= {
  "$",             "DOT",           "PREFIX",        "COLON",
  "IRIREF",        "QNAME",         "BASE",          "SPARQL_BASE",
  "SPARQL_PREFIX",  "SEMICOLON",     "COMMA",         "A",
  "L_SQUARE",      "R_SQUARE",      "L_CURLY",       "R_CURLY",
  "INTEGER_LITERAL",  "DECIMAL_LITERAL",  "DOUBLE_LITERAL",  "LANGTAG",
  "HAT",           "BOOLEAN_LITERAL",  "STRING_LITERAL",  "BLANK_LITERAL",
  "error",         "turtleDoc",     "statements",    "statement",
  "directive",     "triples",       "prefixID",      "base",
  "sparqlPrefix",  "sparqlBase",    "subject",       "predicateObjectList",
  "blankNodePropertyList",  "predicateObjectList_astr",  "verb",          "objectList",
  "predicateObjectList_ast",  "predicateObjectList_qst",  "object",        "objectList_ast",
  "predicate",     "iri",           "blankNode",     "collection",
  "literal",       "rdfLiteral",    "numericalLiteral",  "booleanLiteral",
  "collection_ast",  "string",        "rdfLiteral_qst",  "rdfLiteral_opt",
  "anon",
}
Definition at line 340 of file turtle_parser.c.
Referenced by Parse(), yy_find_shift_action(), yy_pop_parser_stack(), yy_shift(), and yy_syntax_error().
FILE* yyTraceFILE = 0 static
Definition at line 307 of file turtle_parser.c.
Referenced by Parse(), ParseTrace(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), and yyStackOverflow().
char* yyTracePrompt = 0 static
Definition at line 308 of file turtle_parser.c.
Referenced by Parse(), ParseTrace(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), and yyStackOverflow().
const YYMINORTYPE yyzerominor = { 0 } static
Definition at line 128 of file turtle_parser.c.
Referenced by Parse(), and yy_reduce().