ARDP: /Developer/school/ardp/include/ardp/sequence.h File Reference
sequence.h File Reference
#include <stdio.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include "util.h"
Data Structures
struct sequence
Memory container for generic data storage of sequential data.
Macros
#define SEQUENCE_MIN_CAPACITY 8
Typedefs
typedef void(* sequence_error_handler) (void *data)
typedef void(* sequence_free_handler) (void *data)
typedef void(* sequence_print_handler) (void *data)
Functions
struct sequence * sequence_create (sequence_free_handler f, sequence_error_handler e, sequence_print_handler p)
size_t sequence_size (struct sequence *seq)
int sequence_set_at (struct sequence *seq, int idx, void *data)
void * sequence_get_at (struct sequence *seq, int idx)
void * sequence_delete_at (struct sequence *seq, int idx)
void * sequence_pop (struct sequence *seq)
int sequence_push (struct sequence *s, void *data)
int sequence_shift (struct sequence *seq, void *data)
void * sequence_unshift (struct sequence *seq)
void sequence_free (struct sequence *seq)
Detailed Description
Specifies interface for storage with generic item type. Primarily to be used as storage for the RDF:collection.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2016
Definition in file sequence.h.
Macro Definition Documentation
#define SEQUENCE_MIN_CAPACITY 8
Definition at line 25 of file sequence.h.
Referenced by sequence_ensure().
Typedef Documentation
typedef void(* sequence_error_handler) (void *data)
Definition at line 99 of file sequence.h.
typedef void(* sequence_free_handler) (void *data)
Definition at line 100 of file sequence.h.
typedef void(* sequence_print_handler) (void *data)
Definition at line 101 of file sequence.h.
Function Documentation
struct sequence* sequence_create (sequence_free_handler f, sequence_error_handler e, sequence_print_handler p)
Definition at line 47 of file sequence.c.
References sequence::error, sequence::free, sequence::print, and unlikely.
Referenced by main(), and yy_reduce().
void* sequence_delete_at (struct sequence * seq, int idx)
Definition at line 150 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
void sequence_free (struct sequence * seq)
Definition at line 73 of file sequence.c.
References sequence::free, sequence::items, sequence_size(), and sequence_unshift().
Referenced by main(), yy_destructor(), and yy_reduce().
void* sequence_get_at (struct sequence * seq, int idx)
Definition at line 141 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
Referenced by yy_reduce().
void* sequence_pop (struct sequence * seq)
Definition at line 166 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
int sequence_push (struct sequence * s, void * data)
Definition at line 181 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), and sequence::size.
Referenced by main(), and yy_reduce().
int sequence_set_at (struct sequence * seq, int idx, void * data)
Definition at line 94 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), sequence::size, and unlikely.
int sequence_shift (struct sequence * seq, void * data)
Definition at line 202 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), sequence::size, and unlikely.
Referenced by yy_reduce().
size_t sequence_size (struct sequence * seq)
Definition at line 65 of file sequence.c.
References sequence::size, and unlikely.
Referenced by sequence_free(), and yy_reduce().
void* sequence_unshift (struct sequence * seq)
Definition at line 222 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
Referenced by sequence_free(), and yy_reduce().