ARDP: /Developer/school/ardp/src/bin/ardp.c File Reference
ardp.c File Reference
#include "config.h"
#include <dispatch/dispatch.h>
#include <Block.h>
#include <iso646.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <ctype.h>
#include <getopt.h>
#include <zlib.h>
#include <bzlib.h>
#include <ardp/lexer.h>
#include <ardp/parser.h>
#include <ardp/color.h>
#include <ardp/util.h>
Functions
static void help_option_ln (FILE *fs, const char *option, const char *desc)
Helper function to write the application options with support for inteligent color detection and printing.
static void help (FILE *fs)
Help info dump.
static int read_gzip (unsigned char *p, unsigned int len, void *arg)
Read using GZIP method.
static int read_bzip (unsigned char *p, unsigned int len, void *arg)
Read using BZIP method.
static int lexer_error (int level, const char *_Nullable str)
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
static const char ardp_usage_string []
Detailed Description
The main of the ARDP RDF parser.
Todo:
Move auxiliary functions to separate file (help_option_ln, ...)
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2015
Definition in file ardp.c.
Function Documentation
static void help (FILE * fs) static
Help info dump.
Prints the usage help with explanation of each option.
Parameters
[in,out] fs File pointer/stream to dump the info to.
Definition at line 84 of file ardp.c.
References ARDP_COLOR_NORMAL, ardp_fprintf_ln(), help_option_ln(), and PACKAGE_STRING.
Referenced by main().
static void help_option_ln (FILE * fs, const char * option, const char * desc) static
Helper function to write the application options with support for inteligent color detection and printing.
Parameters
[out] fs Pointer to output file/stream
[in] option Option which we are describing.
[in] desc Description of the option
Definition at line 70 of file ardp.c.
References ARDP_COLOR_BOLD, ARDP_COLOR_NORMAL, ardp_fprintf(), and ardp_fprintf_ln().
Referenced by help().
static int lexer_error (int level, const char *_Nullable str) static
Definition at line 132 of file ardp.c.
References ardp_fprintf_ln(), and kARDPColorMagenta.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 137 of file ardp.c.
References ARDP_COLOR_AUTO, ARDP_COLOR_BOLD, ARDP_COLOR_NORMAL, ARDP_COLOR_RED, ardp_config_colorbool(), ardp_fprintf(), ardp_fprintf_ln(), ardp_lexer_create(), ardp_lexer_defaults(), ardp_lexer_destroy(), ardp_lexer_init(), ardp_lexer_process_reader(), ardp_parser_create(), ardp_parser_destroy(), ardp_parser_exec(), ardp_parser_finish(), ardp_parser_set_default_base(), ardp_parser_set_option(), ardp_parser_trace(), ARDP_SUCCESS, ardp_usage_string, ardp_want_color(), ardp_lexer_config::cb, color_stdout_is_tty, DEBUG, die(), ERROR, help(), is, isnt, kARDPColorMagenta, kARDPColorRed, lexer_error(), ardp_lexer_config::logging, not, PACKAGE_STRING, read_bzip(), and read_gzip().
static int read_bzip (unsigned char * p, unsigned int len, void * arg) static
Read using BZIP method.
Parameters
[out] p Pointer to block of memory to be read into.
[in] len Length of the block to be read.
[in] arg File desccriptors and info.
Definition at line 126 of file ardp.c.
Referenced by main().
static int read_gzip (unsigned char * p, unsigned int len, void * arg) static
Read using GZIP method.
Note
Used for reading of *.gz archives and normal *.nt files.
Parameters
[out] p Pointer to block of memory to be read into.
[in] len Length of the block to be read.
[in] arg File desccriptors and info.
Definition at line 113 of file ardp.c.
Referenced by main().
Variable Documentation
const char ardp_usage_string[] static
Initial value:
=
    "usage: " PACKAGE " [-v | --version] [-h | --help] [-u | --usage] <path-to-file>"
    "\n"
    "            [-b | --use-bzip] [-c | --color auto:none:always]"
    "\n"
    "            [-s | --syntax tutle:nt:nq:guess]"
    "\n"
    "            [-w | --verbose <0-7>]"
    "\n"
    "            [-x | --disable-uri-expansion]"
    "\n"
    "            [-z | --disable-curie-expansion]"
    "\n"
    "            [-d | --disable-show-datatype]"
    "\n"
    "            [-y | --enable-lexer-debug]"
    "\n"
    "            [-q | --enable-parser-debug]"
    "\n"
Definition at line 41 of file ardp.c.
Referenced by main().
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 39 of file ardp.c.
Referenced by main().