ARDP: /Developer/school/ardp/src/lib/hashmap.c File Reference
hashmap.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ardp/hashmap.h>
Data Structures
struct map_element
struct map
Macros
#define HASHFUN hash_bkdr
Functions
static unsigned long next_prime (unsigned long n)
map_t map_create (size_t size)
Creates new hashmap.
bool map_resize (map_t *in, size_t room)
Resize the Hash map.
static unsigned long crc32 (const unsigned char *s, size_t len)
static unsigned int map_hash_int_diff (map *m, char *keystring)
static unsigned int map_hash_int (map *m, char *keystring)
static int map_hash (map_t in, char *key)
Return the integer of the location in data to store the point to the item, or MAP_FULL.
static int map_rehash (map_t in)
Doubles the size of the hashmap, and rehashes all the elements.
int map_push (map_t in, char *key, var value)
Add an element to the hashmap.
int map_get (map_t in, char *key, var *arg)
Get an element from the hashmap.
int map_remove (map_t in, char *key)
Remove an element from the hashmap.
int map_iterate (map_t in, map_callback f, var item)
Iteratively call function f with argument (item, data) for each element data in the hashmap.
void map_free (map_t in)
Free the map.
size_t map_size (map_t in)
Get the current size of a hashmap.
size_t map_capacity (map_t in)
Get current capacity of the hashmap.
Variables
static const size_t INITIAL_SIZE = 256
static const int MAX_CHAIN_LENGTH = 8
unsigned int(* hash_callback)(char *keystring)
static const unsigned long num_primes = 28
static const unsigned long prime_list [num_primes]
static unsigned long crc32_tab []
Data Structure Documentation
struct map_element
Definition at line 14 of file hashmap.c.
Data Fields
var data
bool in_use
char * key
struct map
Definition at line 21 of file hashmap.c.
Data Fields
map_element * data
size_t size
size_t table_size
Macro Definition Documentation
#define HASHFUN hash_bkdr
Definition at line 10 of file hashmap.c.
Referenced by map_create().
Function Documentation
static unsigned long crc32 (const unsigned char * s, size_t len) static
Definition at line 186 of file hashmap.c.
References crc32_tab.
Referenced by map_hash_int().
size_t map_capacity (map_t in)
Get current capacity of the hashmap.
Parameters
[in] in Map to be probed.
return Capacity of the hashmap.
Definition at line 429 of file hashmap.c.
References isnt, and map::table_size.
map_t map_create (size_t n)
Creates new hashmap.
Parameters
[in] n Number of the preallocated space.
Returns
Returns new map - or NULL if error occured.
Definition at line 54 of file hashmap.c.
References hash_callback, HASHFUN, is, isnt, map_free(), and next_prime().
Referenced by _add_namespace(), ardp_parser_create_internal(), and main().
void map_free (map_t in)
Free the map.
Parameters
[in] in Map to be unallocated.
Definition at line 415 of file hashmap.c.
References map::data.
Referenced by ardp_parser_destroy_internal(), and map_create().
int map_get (map_t in, char * key, var * arg)
Get an element from the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be used.
[in] arg Item taken from the map.
Returns
Return MAP_OK or MAP_MISSING.
Definition at line 321 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash_int_diff(), MAX_CHAIN_LENGTH, and map::table_size.
Referenced by expand_curie(), main(), and transform_uri().
static int map_hash (map_t in, char * key) static
Return the integer of the location in data to store the point to the item, or MAP_FULL.
Definition at line 224 of file hashmap.c.
References ARDP_MAP_FULL, map::data, map_element::in_use, is, map_element::key, map_hash_int_diff(), MAX_CHAIN_LENGTH, map::size, and map::table_size.
Referenced by map_push().
static unsigned int map_hash_int (map * m, char * keystring) static
Definition at line 201 of file hashmap.c.
References crc32(), and map::table_size.
static unsigned int map_hash_int_diff (map * m, char * keystring) static
Definition at line 196 of file hashmap.c.
References hash_callback, and map::table_size.
Referenced by map_get(), map_hash(), and map_remove().
int map_iterate (map_t in, map_callback f, var item)
Iteratively call function f with argument (item, data) for each element data in the hashmap.
The function must return a map status code.
Note
f must not reenter any hashmap functions, or deadlock may arise.
Parameters
[in] in Map to be manipulated.
[in] f Operation to be performend while iterating the map.
[in] item Item
Returns
If it returns anything other than ARDP_MAP_OK the traversal is treminated.
Definition at line 393 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, isnt, map_size(), and map::table_size.
int map_push (map_t in, char * key, var value)
Add an element to the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be used.
[in] value Value to put in the map.
Returns
Return ARDP_MAP_OK or ARDP_MAP_OMEM.
Definition at line 291 of file hashmap.c.
References ARDP_MAP_FULL, ARDP_MAP_OK, ARDP_MAP_OUTMEM, ARDP_MAP_USED, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash(), map_rehash(), and map::size.
Referenced by _add_namespace(), main(), and map_rehash().
static int map_rehash (map_t in) static
Doubles the size of the hashmap, and rehashes all the elements.
Definition at line 253 of file hashmap.c.
References ARDP_MAP_OK, ARDP_MAP_OUTMEM, map::data, map_push(), next_prime(), not, map::size, and map::table_size.
Referenced by map_push().
int map_remove (map_t in, char * key)
Remove an element from the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be deleted.
Returns
Return MAP_OK or MAP_MISSING.
Definition at line 355 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash_int_diff(), MAX_CHAIN_LENGTH, map::size, and map::table_size.
bool map_resize (map_t * in, size_t room)
Resize the Hash map.
Parameters
[out] in Map to be manipulated.
[in] room Number of elements to add (will floor to nearest prime).
Returns
true if resize is completed, false otherwise.
Definition at line 79 of file hashmap.c.
References map::data, is, next_prime(), and map::table_size.
size_t map_size (map_t in)
Get the current size of a hashmap.
Parameters
[in] in Map to be probed.
Returns
Size of the hashmap.
Definition at line 421 of file hashmap.c.
References isnt, and map::size.
Referenced by map_iterate().
static unsigned long next_prime (unsigned long n) inline static
Definition at line 39 of file hashmap.c.
References num_primes, and prime_list.
Referenced by map_create(), map_rehash(), and map_resize().
Variable Documentation
unsigned long crc32_tab[] static
Definition at line 143 of file hashmap.c.
Referenced by crc32().
unsigned int(* hash_callback) (char *keystring)
Definition at line 11 of file hashmap.c.
Referenced by map_create(), and map_hash_int_diff().
const size_t INITIAL_SIZE = 256 static
Definition at line 7 of file hashmap.c.
const int MAX_CHAIN_LENGTH = 8 static
Definition at line 8 of file hashmap.c.
Referenced by map_get(), map_hash(), and map_remove().
const unsigned long num_primes = 28 static
Definition at line 28 of file hashmap.c.
Referenced by next_prime().
const unsigned long prime_list[num_primes] static
Initial value:
= {
    53ul,        97ul,         193ul,        389ul,       769ul,       1543ul,
    3079ul,      6151ul,       12289ul,      24593ul,     49157ul,     98317ul,
    196613ul,    393241ul,     786433ul,     1572869ul,   3145739ul,   6291469ul,
    12582917ul,  25165843ul,   50331653ul,   100663319ul, 201326611ul, 402653189ul,
    805306457ul, 1610612741ul, 3221225473ul, 4294967291ul
}
Definition at line 29 of file hashmap.c.
Referenced by next_prime().