ARDP: /Developer/school/ardp/include/ardp/parser.h File Reference
parser.h File Reference
#include <ardp/string.h>
#include <ardp/hashmap.h>
#include <ardp/rdf.h>
Data Structures
struct parser
struct datatype_sys_t
struct parser.stats
struct parser.cb
struct parser.extra
Macros
#define _Nullable
#define _Nonnull
#define _Null_unspecified
Functions
int ardp_parser_create (void)
Create and initialize all prerequisites for shared_parser.
void ardp_parser_exec (int type, void *_Nullable value, size_t line, size_t col)
void ardp_parser_finish (void)
Flush parser to end one parsing unit.
void ardp_parser_destroy (void)
Unallocate parser after it is not necessary anymore.
int ardp_parser_add_namespace (utf8 _Nullable qname, utf8 _Nullable iri)
int ardp_parser_set_default_base (const char *_Nullable base)
int ardp_parser_set_option (const uint8_t *_Nullable key, var _Nullable *_Nullable value)
void ardp_parser_trace (void)
Print out parser process.
Detailed Description
Interface for the parser, with the interface for the turtle parser.
Definition in file parser.h.
Data Structure Documentation
struct parser
Parser inner structure which describes its behaviour. It's specific for the TURTLE RDF specification.
For another specifications will require to add other properties.
Definition at line 26 of file parser.h.
Data Fields
utf8 _Nullable base
Bese uri for the <#something> URIs.
struct parser cb
struct parser extra
uint64_t n_bnode
Keeps track of the last blank-node id.
map_t _Nullable namespaces
Namespaces map.
struct parser stats
Statistics for the parser.
struct datatype_sys_t
Definition at line 140 of file parser.h.
Data Fields
utf8 _Nullable datatype
Denotes that the object has datatype.
utf8 _Nullable langtag
Denotes that the object has langtag.
struct parser.stats
Statistics for the parser.
Definition at line 45 of file parser.h.
Data Fields
size_t column
Current column
Note
used to track errors
Warning
Not implemented yet in lexer.
size_t line
Current line
Note
used to track errors
size_t n_directives
Counts the directives found while parsing.
size_t n_errors
Counts error which occured while parsing (lexer's are separate).
size_t n_triples
Triples counter
struct parser.extra
Definition at line 123 of file parser.h.
Data Fields
const char *_Nullable bprefix
int expand_curie
int expand_iri
int show_datatype
Macro Definition Documentation
#define _Nonnull
Definition at line 10 of file parser.h.
#define _Null_unspecified
Definition at line 11 of file parser.h.
#define _Nullable
Definition at line 9 of file parser.h.
Function Documentation
int ardp_parser_add_namespace (utf8 _Nullable qname, utf8 _Nullable iri)
ardp_parser_create (void)
Create and initialize all prerequisites for shared_parser.
Returns
0 if successful, non-zero otherwise.
Definition at line 473 of file test_lemon.c.
Referenced by main().
ardp_parser_destroy (void)
Unallocate parser after it is not necessary anymore.
Destroy shared lexer. And all its underlying structures.
Definition at line 527 of file test_lemon.c.
Referenced by main().
void ardp_parser_exec (int type, void *_Nullable value, size_t line, size_t col)
Referenced by main().
ardp_parser_finish (void)
Flush parser to end one parsing unit.
Signals to parser that we reached end of input (EOF, ...) and that it is supposed to flush all data in buffer.
Note
Equivalent of calling ardp_parser_exec(0,0);
Definition at line 517 of file test_lemon.c.
References Parse(), and shared_parser.
Referenced by main().
int ardp_parser_set_default_base (const char *_Nullable base)
Referenced by main().
int ardp_parser_set_option (const uint8_t *_Nullable key, var _Nullable *_Nullable value)
Referenced by main().
ardp_parser_trace (void)
Print out parser process.
Helps with the debugging of the parser as it writes its current stack as well as reductions and other useful informations.
Definition at line 573 of file test_lemon.c.
References ParseTrace().
Referenced by main().