ARDP: /Developer/school/ardp/include/ardp/lexer.h File Reference
lexer.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <dispatch/dispatch.h>
#include <ardp/util.h>
#include <ardp/string.h>
Data Structures
struct ardp_lexer_config
struct token
Holds the single lexical unit and its value.
struct lexer
Hold informations about the lexer as well as the its internal state.
struct ardp_lexer_config.logging
struct ardp_lexer_config.cb
struct lexer.env
struct lexer.log
struct lexer.cb
Typedefs
typedef int(* _Nullable) (unsigned char *_Nonnull buffer, unsigned len, void *_Nullable arg)
Enumerations
enum lexer_status { ARDP_LEXER_TURTLE_STATUS_UNKNOWN, ARDP_LEXER_TURTLE_STATUS_CREATED, ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED, ARDP_LEXER_TURTLE_STATUS_READY }
Internal state of the lexer used to guard against restricted memory access.
enum lexer_error {
ARDP_ERROR_LEXER_INIT_PREREQUISITE = 101, ARDP_ERROR_LEXER_MALLOC, ARDP_LEXER_READER_NOT_READY, ARDP_LEXER_GENERIC_ERROR,
ARDP_LEXER_ERROR, ARDP_LEXER_OMEM
}
Set of errors, which can be encountered at the runtime of the lexer.
enum lexer_log_level {
ALERT = 1, CRITICAL, ERROR, WARNING,
NOTICE, INFO, DEBUG
}
Functions
int ardp_lexer_create (void)
Create new shared instance of lexer.
int ardp_lexer_defaults ()
Preinitialize lexer with defaults values and prepare it for initialization.
int ardp_lexer_init (struct ardp_lexer_config *_Nullable cfg)
void ardp_lexer_destroy (void)
Destroy the shared instance of the lexer.
int ardp_lexer_state (void)
Get state of the lexer.
bool ardp_lexer_is_ready (void)
Check ready state of the lexer.
int ardp_lexer_process_block (uint8_t *_Nullable p, size_t len, uint8_t *_Nullable mark, bool is_eof)
Lex the block of data.
int ardp_lexer_process_reader (lexer_reader reader, void *_Nullable reader_args)
Process reader until the input is exhausted.
Detailed Description
Define the formal interface for the ARDP lexer (tokenizer) as well as defines the tokens for the turtle (and N-triples) grammar.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2015
Bug:
Internal dispatch queue code needs to be cleaned up and locks need to be set properly (currently not working as designed).
Definition in file lexer.h.
Data Structure Documentation
struct ardp_lexer_config
Definition at line 70 of file lexer.h.
Data Fields
struct ardp_lexer_config cb
struct ardp_lexer_config logging
struct token
Holds the single lexical unit and its value.
: Geared to be Turtle token type - needs to be generalized.
Definition at line 103 of file lexer.h.
Data Fields
char *_Nullable lexem
Actual value of the token (optional)
int type
Enumerated token type
struct lexer
Hold informations about the lexer as well as the its internal state.
Note
The current implementation hides this structure from the user by declaring global variable shared_lexer. This is used for convenience as user don't need to type the lexer in the function call. Future version(s) should include the option to allow user to specify this on their own if they want to overload this for eg.
Definition at line 119 of file lexer.h.
Data Fields
struct lexer cb
Callback used in the lexer
Note
This section was reduced due to rewrite of the lexer states.
struct lexer env
Lexer environment setup used in Ragel.
These variables are required by Ragel to work properly.
dispatch_queue_t _Null_unspecified event_queue
Queue (~thread) for events dispatching.
int finished
Denotes if the lexer is still running (used only in file processing)
Note
Should be moved to callback pointer argument.
dispatch_queue_t _Null_unspecified lexer_queue
Queue (~thread) to run lexer at.
off_t line
Current line count in scanned file/block.
struct lexer log
Debugger and logger helper and level.
enum lexer_status state
Internal state of the lexer.
utf8 _Nullable string
String buffer for the current parsing.
struct lexer.env
Lexer environment setup used in Ragel.
These variables are required by Ragel to work properly.
Definition at line 156 of file lexer.h.
Data Fields
int act
Actual state
int cs
Current state
uint8_t *_Nullable te
Token end
uint8_t *_Nullable ts
Token start
Typedef Documentation
typedef void(^ _Nullable) (int success)
Definition at line 93 of file lexer.h.
Enumeration Type Documentation
enum lexer_error
Set of errors, which can be encountered at the runtime of the lexer.
Enumerator
ARDP_ERROR_LEXER_INIT_PREREQUISITE
ARDP_ERROR_LEXER_MALLOC
ARDP_LEXER_READER_NOT_READY
ARDP_LEXER_GENERIC_ERROR
ARDP_LEXER_ERROR
ARDP_LEXER_OMEM
Definition at line 45 of file lexer.h.
enum lexer_log_level
Enumerator
ALERT
Should be corrected immediately
CRITICAL
Critical conditions
ERROR
Error conditions
WARNING
May indicate that an error will occur if action is not taken.
NOTICE
Events that are unusual, but not error conditions.
INFO
Normal operational messages that require no action.
DEBUG
Information useful to developers for debugging the application.
Definition at line 55 of file lexer.h.
enum lexer_status
Internal state of the lexer used to guard against restricted memory access.
Enumerator
ARDP_LEXER_TURTLE_STATUS_UNKNOWN
ARDP_LEXER_TURTLE_STATUS_CREATED
ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED
ARDP_LEXER_TURTLE_STATUS_READY
Definition at line 34 of file lexer.h.
Function Documentation
int ardp_lexer_create (void)
Create new shared instance of lexer.
Returns
Status of operation. Non-null value if error, zero otherwise.
Definition at line 180 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_destroy(), ARDP_LEXER_TURTLE_STATUS_CREATED, ARDP_SUCCESS, DISPATCH_QUEUE_SERIAL, ERROR, lexer::event_queue, lexer::finished, INFO, is, isnt, lexer::lexer_queue, log(), shared_lexer, lexer::state, unlikely, and WARNING.
Referenced by main().
ardp_lexer_defaults (void)
Preinitialize lexer with defaults values and prepare it for initialization.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 214 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_CREATED, ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED, ARDP_SUCCESS, column, ERROR, INFO, lexer::line, log(), shared_lexer, and lexer::state.
Referenced by main().
void ardp_lexer_destroy (void)
Destroy the shared instance of the lexer.
Clean the lexer with all of its subsidiary structures.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 268 of file turtle.c.
References lexer::event_queue, INFO, isnt, lexer::lexer_queue, log(), shared_lexer, lexer::string, and string_dealloc().
Referenced by ardp_lexer_create(), and main().
int ardp_lexer_init (struct ardp_lexer_config *_Nullable cfg)
Definition at line 235 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED, ARDP_LEXER_TURTLE_STATUS_READY, ARDP_SUCCESS, lexer::cb, lexer::env, ERROR, INFO, log(), lexer::log, shared_lexer, lexer::state, and turtle_start.
Referenced by main().
bool ardp_lexer_is_ready (void)
Check ready state of the lexer.
Shorthand for the ardp_lexer_turtle_state() with probing the state to ARDP_LEXER_STATUS_READY.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 292 of file turtle.c.
References ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_READY, and is.
Referenced by ardp_lexer_process_block(), ardp_lexer_process_reader(), ardp_lexer_process_reader_BUG(), ardp_lexer_process_reader_old(), and ardp_lexer_turtle_process_block().
int ardp_lexer_process_block (uint8_t *_Nullable p, size_t len, uint8_t *_Nullable mark, bool is_eof)
Lex the block of data.
Process single block of data
Parameters
[in] p Data to be processed.
[in] len Length of the data.
[in] mark Helper to process the string marks.
[in] is_eof End of the file indicator.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 299 of file turtle.c.
References A, ARDP_FAILURE, ardp_lexer_is_ready(), ARDP_SUCCESS, BASE, BLANK_LITERAL, BOOLEAN_LITERAL, COMMA, DECIMAL_LITERAL, DOT, DOUBLE_LITERAL, lexer::env, ERROR, lexer::event_queue, lexer::finished, HAT, hex(), INTEGER_LITERAL, IRIREF, L_CURLY, L_ROUND, L_SQUARE, LANGTAG, lexer_emit_token(), lexer_emit_token_const(), lexer_emit_u8_token(), likely, log(), not, PREFIX, QNAME, R_CURLY, R_ROUND, R_SQUARE, SEMICOLON, shared_lexer, SPARQL_BASE, SPARQL_PREFIX, lexer::string, string_append_char(), string_append_utf8(), string_dealloc(), string_finish(), STRING_LITERAL, string_new(), and var.
Referenced by ardp_lexer_process_reader(), and ardp_lexer_process_reader_BUG().
int ardp_lexer_process_reader (lexer_reader reader, void *_Nullable reader_args)
Process reader until the input is exhausted.
Continually process the blocks of data until the reader data stops providing new data to feed the underlying ardp_lexer_turtle_process_block.
Parameters
[in] reader Function pointer to reader more data.
[in] reader_args Additional arguments for the reader.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 13036 of file turtle.c.
References ARDP_LEXER_GENERIC_ERROR, ardp_lexer_is_ready(), ardp_lexer_process_block(), BUFSIZE, lexer::env, lexer::finished, shared_lexer, and turtle_error.
Referenced by main().
int ardp_lexer_state (void)
Get state of the lexer.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 280 of file turtle.c.
References ARDP_LEXER_TURTLE_STATUS_UNKNOWN, is, shared_lexer, and lexer::state.
Referenced by ardp_lexer_defaults(), ardp_lexer_init(), and ardp_lexer_is_ready().