ARDP: /Developer/school/ardp/tests/check_string_copy.c File Reference
check_string_copy.c File Reference
#include <ardp/string.h>
#include <assert.h>
#include <stdio.h>
Functions
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Function Documentation
int main (int argc, char ** argv)
Definition at line 14 of file check_string_copy.c.
References string_copy(), string_create_n(), and string_dealloc().
Variable Documentation
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 12 of file check_string_copy.c.