ARDP: /Developer/school/ardp/tests/check_rdf_term_copy.c File Reference
check_rdf_term_copy.c File Reference
Test to spot regression in rdf_term implemenation.
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ardp/rdf.h>
Functions
int main (int argc, char **argv)
Variables
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Detailed Description
Test to spot regression in rdf_term implemenation.
This files tests the function which copy of term.
Definition in file check_rdf_term_copy.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 17 of file check_rdf_term_copy.c.
References rdf_term_value::blank, rdf_term_value::literal, rdf_term_copy(), rdf_term_free(), rdf_term_from_blank(), rdf_term_from_curie(), rdf_term_from_literal(), rdf_term_from_uri(), rdf_term_literal_value::string, string_create(), string_dealloc(), rdf_term_value::uri, and rdf_term::value.
Variable Documentation
int color_stdout_is_tty = -1
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 15 of file check_rdf_term_copy.c.