ARDP: /Developer/school/ardp/src/lib/parsers/test_lemon.c File Reference
test_lemon.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <ardp/rdf.h>
#include <ardp/parser.h>
#include <ardp/hashmap.h>
#include <ardp/color.h>
#include <ardp/util.h>
#include "turtle_parser.h"
#include "turtle_parser.c"
Macros
#define __STDC_WANT_LIB_EXT1__ 1
Enumerations
enum dir { FRONT, BACK }
Functions
int u8_concatenate (utf8 uri, size_t start)
static int term_uri_append (struct rdf_term *t, utf8 uri, dir direction)
static int uri_has_scheme (struct rdf_term *t)
static int is_relative_uri (struct rdf_term *t)
static int expand_relative_uri (struct rdf_term *t)
static int extract_prefix (struct rdf_term *t, char **prefix, size_t *loc)
static int expand_curie (struct rdf_term *t)
int transform_uri (struct parser *p, struct rdf_term **t)
static int _rebase (utf8 _Nullable base)
static int _add_namespace (utf8 _Nullable qname, utf8 _Nullable iri)
int _triple (struct rdf_statement *s)
utf8 _bnode (void)
static struct parser * ardp_parser_create_internal (void)
Parser ///.
static void ardp_parser_destroy_internal (void)
int ardp_parser_create (void)
Create and initialize all prerequisites for shared_parser.
void ardp_parser_exec (int type, void *value, size_t line, size_t col)
void ardp_parser_finish (void)
Flush parser to end one parsing unit.
void ardp_parser_destroy (void)
Unallocate parser after it is not necessary anymore.
int ardp_parser_set_default_base (const char *base)
int ardp_parser_set_option (const uint8_t *key, var *value)
void ardp_parser_trace (void)
Print out parser process.
Variables
struct parser * shared_parser_internal
static void * shared_parser
Macro Definition Documentation
#define __STDC_WANT_LIB_EXT1__ 1
Definition at line 26 of file test_lemon.c.
Enumeration Type Documentation
enum dir
Enumerator
FRONT
BACK
Definition at line 67 of file test_lemon.c.
Function Documentation
static int _add_namespace (utf8 _Nullable qname, utf8 _Nullable iri) static
Definition at line 287 of file test_lemon.c.
References ARDP_FAILURE, map_create(), map_push(), parser::namespaces, string_copy(), and unlikely.
Referenced by ardp_parser_create_internal().
utf8 _bnode (void)
Definition at line 415 of file test_lemon.c.
References parser::extra, parser::n_bnode, string_create(), and unlikely.
Referenced by ardp_parser_create_internal().
static int _rebase (utf8 _Nullable base) static
Definition at line 273 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, parser::base, string_copy(), string_dealloc(), and unlikely.
Referenced by ardp_parser_create_internal().
int _triple (struct rdf_statement * s)
Definition at line 299 of file test_lemon.c.
References ardp_fprintf(), rdf_term_value::blank, rdf_term_literal_value::datatype, expand_curie(), expand_relative_uri(), parser::extra, kARDPColorBold, kARDPColorGreen, kARDPColorNormal, kARDPColorRed, kARDPColorYellow, rdf_term_literal_value::language, likely, rdf_term_value::literal, rdf_statement::object, rdf_statement::predicate, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_URI, parser::stats, rdf_term_literal_value::string, rdf_statement::subject, rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by ardp_parser_create_internal().
int ardp_parser_create (void)
Create and initialize all prerequisites for shared_parser.
Returns
0 if successful, non-zero otherwise.
Definition at line 473 of file test_lemon.c.
References ardp_parser_create_internal(), ParseAlloc(), and shared_parser.
Referenced by main().
static struct parser* ardp_parser_create_internal (void) static
Parser ///.
Definition at line 431 of file test_lemon.c.
References _add_namespace(), _bnode(), _rebase(), _triple(), parser::cb, map_create(), and parser::namespaces.
Referenced by ardp_parser_create().
void ardp_parser_destroy (void)
Unallocate parser after it is not necessary anymore.
Destroy shared lexer. And all its underlying structures.
Definition at line 527 of file test_lemon.c.
References ardp_parser_destroy_internal(), ParseFree(), and shared_parser.
Referenced by main().
static void ardp_parser_destroy_internal (void) static
Definition at line 445 of file test_lemon.c.
References parser::base, parser::extra, map_free(), parser::namespaces, shared_parser_internal, string_dealloc(), and unlikely.
Referenced by ardp_parser_destroy().
void ardp_parser_exec (int type, void * value, size_t line, size_t col)
Definition at line 498 of file test_lemon.c.
References likely, Parse(), shared_parser, and parser::stats.
void ardp_parser_finish (void)
Flush parser to end one parsing unit.
Signals to parser that we reached end of input (EOF, ...) and that it is supposed to flush all data in buffer.
Note
Equivalent of calling ardp_parser_exec(0,0);
Definition at line 517 of file test_lemon.c.
References Parse(), and shared_parser.
Referenced by main().
int ardp_parser_set_default_base (const char * base)
Definition at line 535 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, parser::base, string_create(), and unlikely.
int ardp_parser_set_option (const uint8_t * key, var * value)
Definition at line 551 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, parser::extra, and string_generic_cmp().
void ardp_parser_trace (void)
Print out parser process.
Helps with the debugging of the parser as it writes its current stack as well as reductions and other useful informations.
Definition at line 573 of file test_lemon.c.
References ParseTrace().
Referenced by main().
static int expand_curie (struct rdf_term * t) static
Definition at line 186 of file test_lemon.c.
References ARDP_FAILURE, ARDP_MAP_MISSING, ARDP_MAP_OK, ARDP_SUCCESS, extract_prefix(), FRONT, map_get(), parser::namespaces, shared_parser_internal, string_copy(), string_strlen(), term_is_curie(), term_uri_append(), u8_concatenate(), unlikely, rdf_term_value::uri, and rdf_term::value.
Referenced by _triple().
static int expand_relative_uri (struct rdf_term * t) static
Definition at line 152 of file test_lemon.c.
References ARDP_FAILURE, parser::base, FRONT, is_relative_uri(), string_copy(), term_is_uri(), and term_uri_append().
Referenced by _triple().
static int extract_prefix (struct rdf_term * t, char ** prefix, size_t * loc) inline static
Definition at line 167 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, ssechr(), rdf_term_value::uri, and rdf_term::value.
Referenced by expand_curie().
static int is_relative_uri (struct rdf_term * t) inline static
Definition at line 145 of file test_lemon.c.
References ARDP_FAILURE, and uri_has_scheme().
Referenced by expand_relative_uri().
static int term_uri_append (struct rdf_term * t, utf8 uri, dir direction) static
Definition at line 84 of file test_lemon.c.
References ARDP_FAILURE, BACK, FRONT, string_append_str(), string_dealloc(), rdf_term_value::uri, and rdf_term::value.
Referenced by expand_curie(), and expand_relative_uri().
int transform_uri (struct parser * p, struct rdf_term ** t)
Definition at line 241 of file test_lemon.c.
References ARDP_MAP_OK, map_get(), parser::namespaces, string_strlen(), token, rdf_term_value::uri, and rdf_term::value.
int u8_concatenate (utf8 uri, size_t start)
Definition at line 46 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, and string_hdr().
Referenced by expand_curie().
static int uri_has_scheme (struct rdf_term * t) inline static
Definition at line 113 of file test_lemon.c.
References ARDP_FAILURE, ARDP_SUCCESS, term_is_uri(), rdf_term_value::uri, and rdf_term::value.
Referenced by is_relative_uri().
Variable Documentation
void* shared_parser static
Opaque parser used by lemon
Definition at line 32 of file test_lemon.c.
Referenced by ardp_parser_create(), ardp_parser_destroy(), ardp_parser_exec(), and ardp_parser_finish().
struct parser* shared_parser_internal
Opaque internal structure of the parser
Definition at line 29 of file test_lemon.c.
Referenced by ardp_parser_destroy_internal(), and expand_curie().