ARDP: /Developer/school/ardp/src/lib/sequence.c File Reference
sequence.c File Reference
#include <ardp/sequence.h>
#include <ardp/util.h>
Functions
static int sequence_ensure (struct sequence *seq, size_t capacity, int grow_at_front)
struct sequence * sequence_create (sequence_free_handler f, sequence_error_handler e, sequence_print_handler p)
size_t sequence_size (struct sequence *seq)
void sequence_free (struct sequence *seq)
int sequence_set_at (struct sequence *seq, int idx, void *data)
void * sequence_get_at (struct sequence *seq, int idx)
void * sequence_delete_at (struct sequence *seq, int idx)
void * sequence_pop (struct sequence *seq)
int sequence_push (struct sequence *s, void *data)
int sequence_shift (struct sequence *seq, void *data)
void * sequence_unshift (struct sequence *seq)
Detailed Description
Implements sequence interface to allow for arbitrary storage of data.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2016
Bug:
sequence_free -> items freeing is causing the segfault. (free disabled for now.)
Definition in file sequence.c.
Function Documentation
struct sequence* sequence_create (sequence_free_handler f, sequence_error_handler e, sequence_print_handler p)
Definition at line 47 of file sequence.c.
References sequence::error, sequence::free, sequence::print, and unlikely.
Referenced by main(), and yy_reduce().
void* sequence_delete_at (struct sequence * seq, int idx)
Definition at line 150 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
static int sequence_ensure (struct sequence * seq, size_t capacity, int grow_at_front) static
Definition at line 15 of file sequence.c.
References sequence::capacity, sequence::head, sequence::items, SEQUENCE_MIN_CAPACITY, and sequence::size.
Referenced by sequence_push(), sequence_set_at(), and sequence_shift().
void sequence_free (struct sequence * seq)
Definition at line 73 of file sequence.c.
References sequence::free, sequence::items, sequence_size(), and sequence_unshift().
Referenced by main(), yy_destructor(), and yy_reduce().
void* sequence_get_at (struct sequence * seq, int idx)
Definition at line 141 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
Referenced by yy_reduce().
void* sequence_pop (struct sequence * seq)
Definition at line 166 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
int sequence_push (struct sequence * s, void * data)
Definition at line 181 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), and sequence::size.
Referenced by main(), and yy_reduce().
int sequence_set_at (struct sequence * seq, int idx, void * data)
Definition at line 94 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), sequence::size, and unlikely.
int sequence_shift (struct sequence * seq, void * data)
Definition at line 202 of file sequence.c.
References sequence::capacity, sequence::free, sequence::head, sequence::items, sequence_ensure(), sequence::size, and unlikely.
Referenced by yy_reduce().
size_t sequence_size (struct sequence * seq)
Definition at line 65 of file sequence.c.
References sequence::size, and unlikely.
Referenced by sequence_free(), and yy_reduce().
void* sequence_unshift (struct sequence * seq)
Definition at line 222 of file sequence.c.
References sequence::head, sequence::items, sequence::size, and unlikely.
Referenced by sequence_free(), and yy_reduce().