ARDP: /Developer/school/ardp/src/lib/rdf/rdf_term.c File Reference
rdf_term.c File Reference
Implementation of the rdf_term
#include <stdlib.h>
#include <ardp/rdf.h>
#include <ardp/util.h>
#include <ardp/string.h>
Functions
struct rdf_term * rdf_term_from_uri (utf8 uri)
struct rdf_term * rdf_term_from_curie (utf8 uri)
struct rdf_term * rdf_term_from_literal (utf8 literal, utf8 lang, utf8 datatype)
struct rdf_term * rdf_term_from_blank (utf8 blank)
struct rdf_term * rdf_term_copy (struct rdf_term *t)
void rdf_term_free (struct rdf_term *t)
int rdf_term_equals (const struct rdf_term *a, const struct rdf_term *b)
int rdf_term_compare (const struct rdf_term *a, const struct rdf_term *b)
Detailed Description
Implementation of the rdf_term
This file implements the rdf_term and all its functions. Term can be one of the following: URI, CURIE, BLANK, LITERAL. Depending on type, the starage is used by internal union.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2016
Definition in file rdf_term.c.
Function Documentation
int rdf_term_compare (const struct rdf_term * a, const struct rdf_term * b)
Definition at line 232 of file rdf_term.c.
References RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, and rdf_term::type.
Referenced by rdf_statement_compare().
struct rdf_term* rdf_term_copy (struct rdf_term * t)
Definition at line 89 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_copy(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), rdf_statement_copy(), and yy_reduce().
int rdf_term_equals (const struct rdf_term * a, const struct rdf_term * b)
Definition at line 162 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_generic_cmp(), string_strlen(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by rdf_statement_equals().
void rdf_term_free (struct rdf_term * t)
Definition at line 128 of file rdf_term.c.
References rdf_term_value::blank, rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_BLANK, RDF_TERM_CURIE, RDF_TERM_LITERAL, RDF_TERM_UNKNOWN, RDF_TERM_URI, rdf_term_literal_value::string, string_dealloc(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), rdf_statement_clear(), rdf_statement_from_nodes(), yy_destructor(), and yy_reduce().
struct rdf_term* rdf_term_from_blank (utf8 blank)
Definition at line 73 of file rdf_term.c.
References rdf_term_value::blank, RDF_TERM_BLANK, string_copy(), rdf_term::type, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_curie (utf8 uri)
Definition at line 37 of file rdf_term.c.
References RDF_TERM_CURIE, string_copy(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_literal (utf8 literal, utf8 lang, utf8 datatype)
Definition at line 52 of file rdf_term.c.
References rdf_term_literal_value::datatype, rdf_term_literal_value::language, rdf_term_value::literal, RDF_TERM_LITERAL, rdf_term_literal_value::string, string_copy(), rdf_term::type, and rdf_term::value.
Referenced by main(), and yy_reduce().
struct rdf_term* rdf_term_from_uri (utf8 uri)
Definition at line 18 of file rdf_term.c.
References RDF_TERM_URI, string_copy(), string_create_n(), string_strlen(), rdf_term::type, rdf_term_value::uri, and rdf_term::value.
Referenced by main(), and yy_reduce().