ARDP: /Developer/school/ardp/tests/check_string.c File Reference
check_string.c File Reference
#include <assert.h>
#include <string.h>
#include <ardp/util.h>
#include <ardp/color.h>
Functions
int main (int argc, char **argv)
Variables
int color_stdout_is_tty
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Function Documentation
int main (int argc, char ** argv)
Definition at line 10 of file check_string.c.
References isnt, string_alloc(), string_append_char(), string_append_utf8(), string_dealloc(), and string_new().
Variable Documentation
int color_stdout_is_tty
Generally the color code will lazily figure this out itself, but this provides a mechanism for callers to override autodetection.
Definition at line 8 of file check_string.c.