ARDP: /Developer/school/ardp/include/ardp/string.h File Reference
string.h File Reference
The ARDP's 'Fat-pointer' string library.
#include <stdbool.h>
#include <stdlib.h>
#include <inttypes.h>
#include "util.h"
#include "color.h"
Typedefs
typedef uint8_t * utf8
Functions
struct __attribute__ ((__packed__)) string_header
Header to use with the string, holding the string informations.
static void string_push (utf8 s, char c)
Push character into the string.
static struct string_header * string_hdr (utf8 str)
Helper function to shift the string to header positio.
uint8_t const * ssechr (uint8_t const *s, uint8_t ch)
Locate first occurrence of character in string.
size_t string_strlen (utf8 str)
Length of the fat-pointer string.
bool string_resize (utf8 *str, size_t size)
Resize the string.
bool string_append_char (utf8 *str, char c)
Append character (BYTE)
bool string_append_utf8 (utf8 *str, int cp)
Append the UTF8 codepoint to the string.
void string_finish (utf8 str)
Close finish the string.
utf8 string_new (void)
Allocate new string with the default length.
utf8 string_alloc (size_t length)
Allocate new string of length.
void string_dealloc (utf8 self)
Destroy the string.
void string_debug (utf8 str)
Debbuging information of the string.
utf8 string_create_n (const uint8_t *s, size_t len, size_t n)
Create new string from content of the buffer of specified length.
utf8 string_create (const uint8_t *s)
Create new string from string buffer.
int string_generic_cmp (const uint8_t *a, const uint8_t *b, int len)
Optimalized compare algorithm yealding little faster string comparison then build-in strcmp function.
int string_prepend (utf8 *src, const uint8_t *str)
Append the C string buffer to the beginning of the ARDP string.
int string_append (utf8 *src, const uint8_t *mod)
Append C string to ardp string container.
int string_append_str (utf8 *src, utf8 mod)
Append two ardp string to one another.
utf8 string_copy (utf8 src)
Returns new copy of the specified string.
Variables
string_header_t
Detailed Description
The ARDP's 'Fat-pointer' string library.
String library used in ARDP to simplify the operations on strings.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2015
Definition in file string.h.
Typedef Documentation
typedef uint8_t* utf8
Definition at line 22 of file string.h.
Function Documentation
struct __attribute__ ((__packed__))
Header to use with the string, holding the string informations.
Current pre-allocated capacity of the string.
Actual lenght of the string (# of characters in buffer).
Definition at line 27 of file string.h.
uint8_t const* ssechr (uint8_t const * s, uint8_t ch)
Locate first occurrence of character in string.
Parameters
[in] s C string.
[in] ch Character to be located. It is passed as its int promotion, but it is internally converted back to char for the comparison.
Note
The terminating null-character is considered part of the C string. Therefore, it can also be located in order to retrieve a pointer to the end of a string.
Returns
position of first character matched, NULL if not found.
Definition at line 41 of file string.c.
Referenced by extract_prefix().
utf8 string_alloc (size_t length)
Allocate new string of length.
Parameters
[in] length Length of the newly allocated string.
Returns
Pointer to the newly created string.
Definition at line 78 of file string.c.
References string_header_t.
Referenced by main(), and string_new().
int string_append (utf8 * src, const uint8_t * mod)
Append C string to ardp string container.
Appends c string buffer to string. The string is resized if necessary. The string buffer being appended needs to be NULL terminated.
Parameters
[in,out] src Pointer to string pointer. (indirection)
[in] mod C string buffer to be appended.
Returns
0 on success, non-zero value if there is error.
Definition at line 133 of file string.c.
References string_hdr().
Referenced by main().
bool string_append_char (utf8 * str, char c)
Append character (BYTE)
Safe version with boundaries checking for apppeding the character to the string.
Parameters
[in,out] str String being manipulated.
[in] c Character being pushed into the string.
Returns
True if character was sucessfully appended, false otherwise.
Definition at line 296 of file string.c.
References ARDP_FAILURE, ARDP_SUCCESS, isnt, string_finish(), string_push(), and string_resize().
Referenced by ardp_lexer_process_block(), ardp_lexer_turtle_process_block(), main(), string_append_utf8(), and test_string_addition_with_realloc().
int string_append_str (utf8 * src, utf8 mod)
Append two ardp string to one another.
Appends string to string. The string is resized if necessary.
Parameters
[in,out] src Pointer to string pointer. (indirection)
[in] mod string buffer to be appended.
Returns
0 on success, non-zero value if there is error.
Definition at line 211 of file string.c.
References ARDP_FAILURE, ARDP_SUCCESS, and string_hdr().
Referenced by main(), string_prepend(), and term_uri_append().
bool string_append_utf8 (utf8 * str, int cp)
Append the UTF8 codepoint to the string.
description
Parameters
[in,out] str String being manipulated.
[in] cp Character codepoint being pushed into the string.
Returns
True if character was sucessfully appended, false otherwise.
Definition at line 305 of file string.c.
References ARDP_FAILURE, ARDP_SUCCESS, isnt, string_append_char(), string_finish(), string_push(), and string_resize().
Referenced by ardp_lexer_process_block(), ardp_lexer_turtle_process_block(), and main().
utf8 string_copy (utf8 src)
Returns new copy of the specified string.
Parameters
[in] src String to be copied.
Returns
Copy of the string.
Definition at line 236 of file string.c.
References string_hdr().
Referenced by _add_namespace(), _rebase(), expand_curie(), expand_relative_uri(), lexer_emit_u8_token(), main(), rdf_term_copy(), rdf_term_from_blank(), rdf_term_from_curie(), rdf_term_from_literal(), rdf_term_from_uri(), and yy_reduce().
utf8 string_create (const uint8_t * s)
Create new string from string buffer.
Parameters
[in] s String buffer to be place in the buffer.
Returns
Pointer to a new string.
Definition at line 112 of file string.c.
References string_create_n().
Referenced by _bnode(), ardp_parser_set_default_base(), main(), and yy_reduce().
utf8 string_create_n (const uint8_t * s, size_t len, size_t n)
Create new string from content of the buffer of specified length.
Parameters
[in] s String buffer to be placed in the new string.
[in] len Length of the s buffer.
[in] n Length to preallocate for buffer.
Returns
New string on success, NULL otherwise.
Note
Doesn't check the memory, copies with for n.
Definition at line 93 of file string.c.
Referenced by lexer_emit_token(), main(), rdf_term_from_uri(), string_create(), string_prepend(), and yy_reduce().
void string_dealloc (utf8 self)
Destroy the string.
As the 'utf8' allocates string header which is hidden from the user, API need to back-shift in the buffer to access it and then delete the whole pointer of the structure.
Parameters
[in] self Pointer to the manipulated string.
Definition at line 256 of file string.c.
References is, and string_hdr().
Referenced by _rebase(), ardp_lexer_destroy(), ardp_lexer_process_block(), ardp_lexer_turtle_process_block(), ardp_parser_destroy_internal(), main(), rdf_term_free(), string_prepend(), term_uri_append(), test_string_addition_with_realloc(), yy_destructor(), and yy_reduce().
void string_debug (utf8 str)
Debbuging information of the string.
Parameters
[in] str String being investigated.
Definition at line 64 of file string.c.
References ARDP_COLOR_GREEN, ARDP_COLOR_MAGENTA, ARDP_COLOR_NORMAL, ARDP_COLOR_YELLOW, ardp_fprintf(), and string_hdr().
void string_finish (utf8 str)
Close finish the string.
In the 'C' the string needs to be NULL-terminated with '\0' and this function provides just that.
Note
we regard this function as safe 'cause the string has preallocated the space to 'allways' accomodate the NUL terminator
Parameters
[in,out] str String being manipulated.
Returns
True if the string was finished corretly, false otherwise.
Definition at line 333 of file string.c.
References string_hdr(), and string_header_t.
Referenced by ardp_lexer_process_block(), ardp_lexer_turtle_process_block(), string_append_char(), and string_append_utf8().
int string_generic_cmp (const uint8_t * a, const uint8_t * b, int len)
Optimalized compare algorithm yealding little faster string comparison then build-in strcmp function.
Parameters
[in] a First string
[in] b Second string
[in] len Length to compare.
Returns
1 iff string are the same, 0 otherwise.
Definition at line 339 of file string.c.
Referenced by ardp_parser_set_option(), main(), and rdf_term_equals().
static struct string_header* string_hdr (utf8 str) static
Helper function to shift the string to header positio.
Parameters
[in] str String to access.
Returns
Returns the hidden star of the string.
Definition at line 62 of file string.h.
References string_header_t.
Referenced by ardp_parser_set_base_uri(), string_append(), string_append_str(), string_copy(), string_dealloc(), string_debug(), string_finish(), string_prepend(), string_resize(), string_strlen(), and u8_concatenate().
utf8 string_new (void)
Allocate new string with the default length.
Returns
Pointer to the newly created string.
Definition at line 249 of file string.c.
References INITIAL_CAPACITY, and string_alloc().
Referenced by ardp_lexer_process_block(), ardp_lexer_turtle_process_block(), main(), and test_string_addition_with_realloc().
int string_prepend (utf8 * src, const uint8_t * str)
Append the C string buffer to the beginning of the ARDP string.
This function creates new string with the content of the C string buffer and then appends the rest using the string_append function. As the new string already has space for the new string, it doesn't require second realloc.
Parameters
[in,out] src Source string to be appended to.
[in] str C string buffer to be prepended.
Returns
0 on success, non-zero value otherwise.
Note
err=1 - couldn't create new string.
err=2 - couldn't append the string.
Definition at line 173 of file string.c.
References string_append_str(), string_create_n(), string_dealloc(), and string_hdr().
static void string_push (utf8 s, char c) inline static
Push character into the string.
The helper pushing the raw character to the string.
Note
This function is unsafe and should be allways used with the proper bounds check.
Parameters
[in,out] s String being manipulated.
[in] c Character to be appended to string.
Definition at line 50 of file string.h.
References string_header_t.
Referenced by string_append_char(), and string_append_utf8().
bool string_resize (utf8 * str, size_t size)
Resize the string.
This function checks if there is enougth space in the string or if the space need to be added. In case that the space is inssuficient, it allocates twice as much until the 'MAX_PREALLOC' is reached when the new preallocation is then created allways with it's size.
Parameters
[in,out] str Pointer to String currently being manipulated.
[in] size Size to check/allocate.
Returns
True if string is ready to accomodate the size, no otherwise.
Definition at line 265 of file string.c.
References ARDP_FAILURE, ARDP_SUCCESS, is, MAX_PREALLOC, string_hdr(), and string_header_t.
Referenced by string_append_char(), and string_append_utf8().
size_t string_strlen (utf8 str)
Length of the fat-pointer string.
Parameters
[in] str String for measurement.
Returns
Return the length of the string.
Definition at line 59 of file string.c.
References string_hdr().
Referenced by expand_curie(), main(), rdf_term_equals(), rdf_term_from_uri(), and transform_uri().
Variable Documentation
string_header_t
Definition at line 36 of file string.h.
Referenced by ardp_parser_set_base_uri(), string_alloc(), string_finish(), string_hdr(), string_push(), and string_resize().