ARDP: /Developer/school/ardp/src/lib/rdf/rdf_statement.c File Reference
rdf_statement.c File Reference
#include <ardp/rdf.h>
Functions
struct rdf_statement * rdf_statement_create (void)
Create new empty RDF statement.
struct rdf_statement * rdf_statement_from_nodes (struct rdf_term *subject, struct rdf_term *predicate, struct rdf_term *object, struct rdf_term *graph)
struct rdf_statement * rdf_statement_copy (struct rdf_statement *s)
void rdf_statement_zero (struct rdf_statement *s)
void rdf_statement_clear (struct rdf_statement *s)
void rdf_statement_free (struct rdf_statement *s)
int rdf_statement_compare (struct rdf_statement *a, struct rdf_statement *b)
int rdf_statement_equals (struct rdf_statement *a, struct rdf_statement *b)
Detailed Description
Implements the RDF 'statement' interfaces declared in rdf.h.
Author
Tomas Michalek tomas.nosp@m..mic.nosp@m.halek.nosp@m..st@.nosp@m.vsb.c.nosp@m.z
Date
2016
Definition in file rdf_statement.c.
Function Documentation
void rdf_statement_clear (struct rdf_statement * s)
Definition at line 67 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_free(), and rdf_statement::subject.
Referenced by rdf_statement_free().
int rdf_statement_compare (struct rdf_statement * a, struct rdf_statement * b)
Definition at line 89 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_compare(), and rdf_statement::subject.
struct rdf_statement* rdf_statement_copy (struct rdf_statement * s)
Definition at line 42 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_statement_create(), rdf_term_copy(), and rdf_statement::subject.
Referenced by main().
struct rdf_statement* rdf_statement_create (void)
Create new empty RDF statement.
Returns
Statement, NULL on error.
Definition at line 12 of file rdf_statement.c.
Referenced by rdf_statement_copy(), and rdf_statement_from_nodes().
int rdf_statement_equals (struct rdf_statement * a, struct rdf_statement * b)
Definition at line 119 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_term_equals(), and rdf_statement::subject.
void rdf_statement_free (struct rdf_statement * s)
Definition at line 79 of file rdf_statement.c.
References rdf_statement_clear().
Referenced by main(), and yy_reduce().
struct rdf_statement* rdf_statement_from_nodes (struct rdf_term * subject, struct rdf_term * predicate, struct rdf_term * object, struct rdf_term * graph)
Definition at line 18 of file rdf_statement.c.
References rdf_statement::graph, rdf_statement::object, rdf_statement::predicate, rdf_statement_create(), rdf_term_free(), and rdf_statement::subject.
Referenced by main(), and yy_reduce().
void rdf_statement_zero (struct rdf_statement * s)
Definition at line 61 of file rdf_statement.c.