ARDP: /Developer/school/ardp/include/ardp/hashmap.h File Reference
hashmap.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <ardp/util.h>
#include <ardp/hash.h>
Typedefs
typedef int(* map_callback) (var a, var b)
Pointer to function that can take two var arguments and return an integer.
typedef var map_t
Pointer to internally maintained data structure.
Functions
map_t map_create (size_t n)
Creates new hashmap.
bool map_resize (map_t *in, size_t room)
Resize the Hash map.
map_t map_realloc (unsigned int n)
Realloc the hashmap.
int map_iterate (map_t in, map_callback f, var item)
Iteratively call function f with argument (item, data) for each element data in the hashmap.
int map_push (map_t in, char *key, var value)
Add an element to the hashmap.
int map_get (map_t in, char *key, var *arg)
Get an element from the hashmap.
int map_remove (map_t in, char *key)
Remove an element from the hashmap.
int map_get_one (map_t in, var *arg, int remove)
Get any element.
void map_free (map_t in)
Free the map.
size_t map_size (map_t in)
Get the current size of a hashmap.
size_t map_capacity (map_t in)
Get current capacity of the hashmap.
Variables
static const int ARDP_MAP_USED = (-4)
static const int ARDP_MAP_MISSING = (-3)
static const int ARDP_MAP_FULL = (-2)
static const int ARDP_MAP_OUTMEM = (-1)
static const int ARDP_MAP_OK = (0)
Typedef Documentation
typedef int(* map_callback) (var a, var b)
Pointer to function that can take two var arguments and return an integer.
Parameters
[in] a Argument A
[in] b Argument B
Returns
Returns status code.
Definition at line 49 of file hashmap.h.
typedef var map_t
Pointer to internally maintained data structure.
HashMap client do not need to know how the hashmaps are represented. They only manipulate the map_t data types.
Definition at line 57 of file hashmap.h.
Function Documentation
size_t map_capacity (map_t in)
Get current capacity of the hashmap.
Parameters
[in] in Map to be probed.
return Capacity of the hashmap.
Definition at line 429 of file hashmap.c.
References isnt, and map::table_size.
map_t map_create (size_t n)
Creates new hashmap.
Parameters
[in] n Number of the preallocated space.
Returns
Returns new map - or NULL if error occured.
Definition at line 54 of file hashmap.c.
References hash_callback, HASHFUN, is, isnt, map_free(), and next_prime().
Referenced by _add_namespace(), ardp_parser_create_internal(), and main().
void map_free (map_t in)
Free the map.
Parameters
[in] in Map to be unallocated.
Definition at line 415 of file hashmap.c.
References map::data.
Referenced by ardp_parser_destroy_internal(), and map_create().
int map_get (map_t in, char * key, var * arg)
Get an element from the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be used.
[in] arg Item taken from the map.
Returns
Return MAP_OK or MAP_MISSING.
Definition at line 321 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash_int_diff(), MAX_CHAIN_LENGTH, and map::table_size.
Referenced by expand_curie(), main(), and transform_uri().
int map_get_one (map_t in, var * arg, int remove)
Get any element.
Parameters
[in] in Map to be manipulated.
[in] arg item taken from the map.
[in] remove Indicates if the item should be deleted
Returns
Return MAP_OK or MAP_MISSING.
int map_iterate (map_t in, map_callback f, var item)
Iteratively call function f with argument (item, data) for each element data in the hashmap.
The function must return a map status code.
Note
f must not reenter any hashmap functions, or deadlock may arise.
Parameters
[in] in Map to be manipulated.
[in] f Operation to be performend while iterating the map.
[in] item Item
Returns
If it returns anything other than ARDP_MAP_OK the traversal is treminated.
Definition at line 393 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, isnt, map_size(), and map::table_size.
int map_push (map_t in, char * key, var value)
Add an element to the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be used.
[in] value Value to put in the map.
Returns
Return ARDP_MAP_OK or ARDP_MAP_OMEM.
Definition at line 291 of file hashmap.c.
References ARDP_MAP_FULL, ARDP_MAP_OK, ARDP_MAP_OUTMEM, ARDP_MAP_USED, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash(), map_rehash(), and map::size.
Referenced by _add_namespace(), main(), and map_rehash().
map_t map_realloc (unsigned int n)
Realloc the hashmap.
int map_remove (map_t in, char * key)
Remove an element from the hashmap.
Parameters
[in] in Map to be manipulated.
[in] key Key to be deleted.
Returns
Return MAP_OK or MAP_MISSING.
Definition at line 355 of file hashmap.c.
References ARDP_MAP_MISSING, ARDP_MAP_OK, map_element::data, map::data, map_element::in_use, is, map_element::key, map_hash_int_diff(), MAX_CHAIN_LENGTH, map::size, and map::table_size.
bool map_resize (map_t * in, size_t room)
Resize the Hash map.
Parameters
[out] in Map to be manipulated.
[in] room Number of elements to add (will floor to nearest prime).
Returns
true if resize is completed, false otherwise.
Definition at line 79 of file hashmap.c.
References map::data, is, next_prime(), and map::table_size.
size_t map_size (map_t in)
Get the current size of a hashmap.
Parameters
[in] in Map to be probed.
Returns
Size of the hashmap.
Definition at line 421 of file hashmap.c.
References isnt, and map::size.
Referenced by map_iterate().
Variable Documentation
const int ARDP_MAP_FULL = (-2) static
HashMap is full.
Definition at line 30 of file hashmap.h.
Referenced by map_hash(), and map_push().
const int ARDP_MAP_MISSING = (-3) static
No such element in map.
Definition at line 26 of file hashmap.h.
Referenced by expand_curie(), map_get(), map_iterate(), and map_remove().
const int ARDP_MAP_OK = (0) static
OK - operation was performend correctly.
Definition at line 38 of file hashmap.h.
Referenced by expand_curie(), map_get(), map_iterate(), map_push(), map_rehash(), map_remove(), and transform_uri().
const int ARDP_MAP_OUTMEM = (-1) static
Out of memory.
Definition at line 34 of file hashmap.h.
Referenced by map_push(), and map_rehash().
const int ARDP_MAP_USED = (-4) static
Key used in the map.
Definition at line 22 of file hashmap.h.
Referenced by map_push().