ARDP: /Developer/school/ardp/src/lib/lexers/turtle.c File Reference
turtle.c File Reference
#include "config.h"
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <iso646.h>
#include <string.h>
#include <assert.h>
#include <dispatch/dispatch.h>
#include <ardp/lexer.h>
#include <ardp/lexer.turtle.h>
#include <ardp/util.h>
#include <ardp/color.h>
Macros
#define BUFSIZE (0x10000)
#define var(s) (shared_lexer->env.s)
#define DISPATCH_QUEUE_SERIAL NULL
Functions
static uint32_t hex (const unsigned char *src, unsigned int len)
static void log (int level, const char *message)
static void lexer_emit_u8_token (enum turtle_token_type type)
static void lexer_emit_token (enum turtle_token_type type, uint8_t *_Nullable str, size_t len)
static void lexer_emit_token_const (enum turtle_token_type type)
void ardp_lexer_turtle_debug (void)
bool dispatch_queue_isempty (dispatch_queue_t queue)
int ardp_lexer_create (void)
Create new shared instance of lexer.
int ardp_lexer_defaults (void)
Preinitialize lexer with defaults values and prepare it for initialization.
int ardp_lexer_init (struct ardp_lexer_config *_Nullable cfg)
void ardp_lexer_destroy ()
Destroy the shared instance of the lexer.
int ardp_lexer_state ()
Get state of the lexer.
bool ardp_lexer_is_ready ()
Check ready state of the lexer.
int ardp_lexer_process_block (uint8_t *_Nullable v, size_t len, uint8_t *_Nullable mark, bool is_eof)
Lex the block of data.
void ardp_lexer_turtle_process_block (uint8_t *_Nullable v, size_t len, uint8_t *_Nullable mark, bool is_eof, completation_block handler)
int ardp_lexer_process_reader (lexer_reader reader, void *_Nullable reader_args)
Process reader until the input is exhausted.
int ardp_lexer_process_reader_BUG (lexer_reader reader, void *_Nullable reader_args)
void ardp_lexer_process_reader_old (lexer_reader reader, void *_Nullable reader_args, completation_block handler)
Variables
static struct lexer *_Nullable shared_lexer
static uint8_t * column
static const int turtle_start = 188
static const int turtle_first_final = 188
static const int turtle_error = -1
static const int turtle_en_main = 188
Macro Definition Documentation
#define BUFSIZE (0x10000)
Definition at line 38 of file turtle.c.
Referenced by ardp_lexer_process_reader(), ardp_lexer_process_reader_BUG(), and ardp_lexer_process_reader_old().
#define DISPATCH_QUEUE_SERIAL NULL
Referenced by ardp_lexer_create().
#define var (s) (shared_lexer->env.s)
Shorthand to speedup token input.
Definition at line 73 of file turtle.c.
Referenced by ardp_lexer_process_block(), and ardp_lexer_turtle_process_block().
Function Documentation
int ardp_lexer_create (void)
Create new shared instance of lexer.
Returns
Status of operation. Non-null value if error, zero otherwise.
Definition at line 180 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_destroy(), ARDP_LEXER_TURTLE_STATUS_CREATED, ARDP_SUCCESS, DISPATCH_QUEUE_SERIAL, ERROR, lexer::event_queue, lexer::finished, INFO, is, isnt, lexer::lexer_queue, log(), shared_lexer, lexer::state, unlikely, and WARNING.
Referenced by main().
int ardp_lexer_defaults (void)
Preinitialize lexer with defaults values and prepare it for initialization.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 214 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_CREATED, ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED, ARDP_SUCCESS, column, ERROR, INFO, lexer::line, log(), shared_lexer, and lexer::state.
Referenced by main().
void ardp_lexer_destroy (void)
Destroy the shared instance of the lexer.
Clean the lexer with all of its subsidiary structures.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 268 of file turtle.c.
References lexer::event_queue, INFO, isnt, lexer::lexer_queue, log(), shared_lexer, lexer::string, and string_dealloc().
Referenced by ardp_lexer_create(), and main().
int ardp_lexer_init (struct ardp_lexer_config *_Nullable cfg)
Definition at line 235 of file turtle.c.
References ARDP_FAILURE, ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_PREINITIALIZED, ARDP_LEXER_TURTLE_STATUS_READY, ARDP_SUCCESS, lexer::cb, lexer::env, ERROR, INFO, log(), lexer::log, shared_lexer, lexer::state, and turtle_start.
Referenced by main().
bool ardp_lexer_is_ready (void)
Check ready state of the lexer.
Shorthand for the ardp_lexer_turtle_state() with probing the state to ARDP_LEXER_STATUS_READY.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 292 of file turtle.c.
References ardp_lexer_state(), ARDP_LEXER_TURTLE_STATUS_READY, and is.
Referenced by ardp_lexer_process_block(), ardp_lexer_process_reader(), ardp_lexer_process_reader_BUG(), ardp_lexer_process_reader_old(), and ardp_lexer_turtle_process_block().
int ardp_lexer_process_block (uint8_t *_Nullable p, size_t len, uint8_t *_Nullable mark, bool is_eof)
Lex the block of data.
Process single block of data
Parameters
[in] p Data to be processed.
[in] len Length of the data.
[in] mark Helper to process the string marks.
[in] is_eof End of the file indicator.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 299 of file turtle.c.
References A, ARDP_FAILURE, ardp_lexer_is_ready(), ARDP_SUCCESS, BASE, BLANK_LITERAL, BOOLEAN_LITERAL, COMMA, DECIMAL_LITERAL, DOT, DOUBLE_LITERAL, lexer::env, ERROR, lexer::event_queue, lexer::finished, HAT, hex(), INTEGER_LITERAL, IRIREF, L_CURLY, L_ROUND, L_SQUARE, LANGTAG, lexer_emit_token(), lexer_emit_token_const(), lexer_emit_u8_token(), likely, log(), not, PREFIX, QNAME, R_CURLY, R_ROUND, R_SQUARE, SEMICOLON, shared_lexer, SPARQL_BASE, SPARQL_PREFIX, lexer::string, string_append_char(), string_append_utf8(), string_dealloc(), string_finish(), STRING_LITERAL, string_new(), and var.
Referenced by ardp_lexer_process_reader(), and ardp_lexer_process_reader_BUG().
int ardp_lexer_process_reader (lexer_reader reader, void *_Nullable reader_args)
Process reader until the input is exhausted.
Continually process the blocks of data until the reader data stops providing new data to feed the underlying ardp_lexer_turtle_process_block.
Parameters
[in] reader Function pointer to reader more data.
[in] reader_args Additional arguments for the reader.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 13036 of file turtle.c.
References ARDP_LEXER_GENERIC_ERROR, ardp_lexer_is_ready(), ardp_lexer_process_block(), BUFSIZE, lexer::env, lexer::finished, shared_lexer, and turtle_error.
Referenced by main().
int ardp_lexer_process_reader_BUG (lexer_reader reader, void *_Nullable reader_args)
Definition at line 13125 of file turtle.c.
References ARDP_LEXER_GENERIC_ERROR, ardp_lexer_is_ready(), ARDP_LEXER_OMEM, ardp_lexer_process_block(), BUFSIZE, dispatch_queue_isempty(), lexer::env, lexer::event_queue, lexer::finished, lexer::lexer_queue, shared_lexer, and turtle_error.
void ardp_lexer_process_reader_old (lexer_reader reader, void *_Nullable reader_args, completation_block handler)
Definition at line 13182 of file turtle.c.
References ARDP_LEXER_ERROR, ARDP_LEXER_GENERIC_ERROR, ardp_lexer_is_ready(), ARDP_LEXER_OMEM, ARDP_LEXER_READER_NOT_READY, ardp_lexer_turtle_process_block(), ARDP_SUCCESS, BUFSIZE, lexer::env, lexer::finished, is, isnt, not, shared_lexer, and turtle_error.
int ardp_lexer_state (void)
Get state of the lexer.
Returns
Status of operation. Non-null if error, zero otherwise.
Definition at line 280 of file turtle.c.
References ARDP_LEXER_TURTLE_STATUS_UNKNOWN, is, shared_lexer, and lexer::state.
Referenced by ardp_lexer_defaults(), ardp_lexer_init(), and ardp_lexer_is_ready().
void ardp_lexer_turtle_debug (void)
Definition at line 146 of file turtle.c.
References shared_lexer, and lexer::state.
void ardp_lexer_turtle_process_block (uint8_t *_Nullable v, size_t len, uint8_t *_Nullable mark, bool is_eof, completation_block handler)
Definition at line 6664 of file turtle.c.
References A, ARDP_FAILURE, ardp_lexer_is_ready(), ARDP_SUCCESS, BASE, BLANK_LITERAL, BOOLEAN_LITERAL, COMMA, DECIMAL_LITERAL, DOT, DOUBLE_LITERAL, lexer::env, lexer::event_queue, lexer::finished, HAT, hex(), INTEGER_LITERAL, IRIREF, L_CURLY, L_ROUND, L_SQUARE, LANGTAG, lexer_emit_token(), lexer_emit_token_const(), lexer_emit_u8_token(), likely, PREFIX, QNAME, R_CURLY, R_ROUND, R_SQUARE, SEMICOLON, shared_lexer, SPARQL_BASE, SPARQL_PREFIX, lexer::string, string_append_char(), string_append_utf8(), string_dealloc(), string_finish(), STRING_LITERAL, string_new(), and var.
Referenced by ardp_lexer_process_reader_old().
bool dispatch_queue_isempty (dispatch_queue_t queue)
Definition at line 155 of file turtle.c.
Referenced by ardp_lexer_process_reader_BUG().
static uint32_t hex (const unsigned char * src, unsigned int len) static
Converst constrained string buffer to unsigned integer.
Parameters
[in] src String to probe.
[in] len Length to probe.
Returns
UTF-8 codepoint.
Definition at line 56 of file turtle.c.
Referenced by ardp_lexer_process_block(), and ardp_lexer_turtle_process_block().
static void lexer_emit_token (enum turtle_token_type type, uint8_t *_Nullable str, size_t len) static
Definition at line 120 of file turtle.c.
References lexer::cb, lexer::event_queue, likely, shared_lexer, and string_create_n().
Referenced by ardp_lexer_process_block(), and ardp_lexer_turtle_process_block().
static void lexer_emit_token_const (enum turtle_token_type type) static
Definition at line 135 of file turtle.c.
References lexer::cb, lexer::event_queue, likely, and shared_lexer.
Referenced by ardp_lexer_process_block(), and ardp_lexer_turtle_process_block().
static void lexer_emit_u8_token (enum turtle_token_type type) static
Definition at line 104 of file turtle.c.
References lexer::cb, lexer::event_queue, likely, shared_lexer, lexer::string, and string_copy().
Referenced by ardp_lexer_process_block(), and ardp_lexer_turtle_process_block().
static void log (int level, const char * message) static
Definition at line 95 of file turtle.c.
References lexer::log, and shared_lexer.
Referenced by ardp_lexer_create(), ardp_lexer_defaults(), ardp_lexer_destroy(), ardp_lexer_init(), and ardp_lexer_process_block().
Variable Documentation
uint8_t* column static
Holds the column reference point
Definition at line 46 of file turtle.c.
Referenced by ardp_lexer_defaults().
struct lexer* _Nullable shared_lexer static
Global variable holding the shared lexer;
Definition at line 43 of file turtle.c.
Referenced by ardp_lexer_create(), ardp_lexer_defaults(), ardp_lexer_destroy(), ardp_lexer_init(), ardp_lexer_process_block(), ardp_lexer_process_reader(), ardp_lexer_process_reader_BUG(), ardp_lexer_process_reader_old(), ardp_lexer_state(), ardp_lexer_turtle_debug(), ardp_lexer_turtle_process_block(), lexer_emit_token(), lexer_emit_token_const(), lexer_emit_u8_token(), and log().
const int turtle_en_main = 188 static
Definition at line 83 of file turtle.c.
const int turtle_error = -1 static
Definition at line 81 of file turtle.c.
Referenced by ardp_lexer_process_reader(), ardp_lexer_process_reader_BUG(), and ardp_lexer_process_reader_old().
const int turtle_first_final = 188 static
Definition at line 80 of file turtle.c.
const int turtle_start = 188 static
Definition at line 79 of file turtle.c.
Referenced by ardp_lexer_init().