#define DOT                             1
#define PREFIX                          2
#define COLON                           3
#define IRIREF                          4
#define QNAME                           5
#define BASE                            6
#define SPARQL_BASE                     7
#define SPARQL_PREFIX                   8
#define SEMICOLON                       9
#define COMMA                          10
#define A                              11
#define L_SQUARE                       12
#define R_SQUARE                       13
#define L_CURLY                        14
#define R_CURLY                        15
#define INTEGER_LITERAL                16
#define DECIMAL_LITERAL                17
#define DOUBLE_LITERAL                 18
#define LANGTAG                        19
#define HAT                            20
#define BOOLEAN_LITERAL                21
#define STRING_LITERAL                 22
#define BLANK_LITERAL                  23
